### ISSUE TITLE
WebFrame does not position correctly on secondary display on OS X

### ISSUE THREAD

**Issue by Subject22** [mgarin/weblaf#156]
I don't appear to be able to move a WebFrame up any higher than shown in the screenshot. It seems to hit an invisible barrier. 
![screen shot 2014-07-14 at 11 52 36 pm 2](https://cloud.githubusercontent.com/assets/4090877/3570320/919dbd70-0b4d-11e4-8643-37bf82f5af1b.png)

Maximising the window produces odd results, as shown. The window appears too low on the page, and the bottom of the window is cut off. Again, I am unable to move the window any higher.

![screen shot 2014-07-15 at 12 00 56 am 2](https://cloud.githubusercontent.com/assets/4090877/3570370/8c958050-0b4e-11e4-842e-e0cbdc38dfb2.png)

I have no problems with resizing or maximising on my primary display. My primary display is 1920x1080 and my secondary is 1920x1200, if that's relevant.

Thanks for your help! :)

I'm using WebLaF 1.28 [preview]

**Comment by mgarin** [comment]
Sorry for the really late update on this one, but here it goes...

---

About the first case - it basically happens due to two things:
1. Mac OS X doesn't allow any frame to go higher than its task bar
2. WebLaF uses a transparent background trick to draw window shade
As the result - actual WebLaF frame size is much bigger than you think it is and Mac OS X works with the "real" size of the frame and include the shadow into that size.

Unfortunately there isn't much I can do about it. There are two solutions:
1. Don't use custom frame decoration
2. Disable shade on the frame so that it's actual size will be the same as the visible one

There might be another way to enable native Mac OS X window shade - use custom client properties to enable it. All custom Swing settings for Mac OS X are perfectly described by this article:
http://nadeausoftware.com/articles/2009/01/mac_java_tip_how_control_window_decorations
I might also include some of those settings in next WebLaF updates.

---

Second issue was most probably related to another issue I have fixed not so long ago: #195
It was an issue of custom frame decoration maximize behavior, it should be working properly now.

---

So generally this should wrap up the issues described, so I will be closing this ticket.
Feel free to reopen it if something is still wrong.

I have also added a separate enhancement issue for the next update to include custom options for Mac OS X from the article I have mentioned above: #240

**Comment by mgarin** [comment]
Updated pre-release artifacts are now available here:
http://weblookandfeel.com/downloads/prerelease/
