### ISSUE TITLE
Unable to drag WebCalendar into JPanel in NetBeans

### ISSUE THREAD

**Issue by shuai-zh** [mgarin/weblaf#208]
![image](https://cloud.githubusercontent.com/assets/1223136/5286730/edaa6f48-7af4-11e4-8a8b-e043fc6080ad.png)

The detailed exceptions are:
![image](https://cloud.githubusercontent.com/assets/1223136/5286769/3e4884da-7af5-11e4-8422-0f8037d93e54.png)

**Comment by iamchathu** [comment]
Have same error. :cry:

**Comment by mgarin** [comment]
Language exception occurs because of the way components are dependant on managers initialization. Pretty much WebLaF managers should be initialized before you create any component, otherwise you will might get a set of exceptions. 

This will be fixed soon along with some other initialization improvements. 

I'll close this issue to keep a single one related to NetBeans: #18
