### ISSUE TITLE
Using WebPopOver with owner-component in WebWindow throws java.lang.IllegalArgumentException: Wrong parent window

### ISSUE THREAD

**Issue by fpdev** [mgarin/weblaf#213]
I would like to create a WebPopOver whose owner is a Component that resides in a WebWindow. 

WebPopOver calls the WebDialog(final Component owner)-constructor which calls SwingUtils.getWindowAncestor(owner) which indeed returns a Window (ie. the WebWindow in which the owner-component resides). However, as WebDialog calls the JDialog super-constructor which actually needs a Dialog or Frame not just a Window (see JavaDoc), an IllegalArgumentException is thrown.

Stacktrace-Excerpt:
```
    Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Wrong parent window
    	at java.awt.Dialog.<init>(Unknown Source)
    	at javax.swing.JDialog.<init>(Unknown Source)
    	at javax.swing.JDialog.<init>(Unknown Source)
    	at javax.swing.JDialog.<init>(Unknown Source)
    	at com.alee.laf.rootpane.WebDialog.<init>(WebDialog.java:124)
    	at com.alee.extended.window.WebPopOver.<init>(WebPopOver.java:157)
    	at com.github.bfour.fpjgui.abstraction.feedback.InPlaceFeedbackPopoverSpawner.feedbackBroadcasted(InPlaceFeedbackPopoverSpawner.java:52)
```
Do you know any way around this?

**Comment by mgarin** [comment]
First time I actually encounter this problem, but it seems to be true that `JDialog` (or simple `Dialog`) cannot be opened on top of `Window` or `JWindow` (or `WebWindow`). Unfortunately I doubt that there is any kind of good workaround to setup `Window` or `JWindow` as `JDialog`'s parent since the check that throws exception is setup directly in constructors of `Dialog`.

Here are some possible options:

1. Use something instead of `JWindow` - for example non-modal `JDialog` with decoration switched off and without a parent, it will be acting the same way in most possible cases.

2. Do not specify `WebPopOver` parent when opening it - in some cases that will not cause any problems. Though this should be checked for each case specifically.

3. Create a nasty construction call that will create `WebPopOver` through `Unsafe` without calling class constructor (yeah, it can be done), then initialize all the variables needed manually through reflection call to appropriate methods inside `Dialog`, `JDialog` and `WebPopOver`.

About the creating class without calling its constructor:
```
final WebPopOver popOver = ( WebPopOver ) Unsafe.getUnsafe ().allocateInstance ( WebPopOver.class );
```
Though I really don't recommend that way as you will have to ensure that you call everything right and support that code after JDK/LaF updates so it would always initialize properly.

**Comment by mgarin** [comment]
Will close it for now.
Feel free to reopen if you have any tips how to workaround or open new issue for another question :)
