### ISSUE TITLE
CheckBox and RadioButton - inconsistent border style?

### ISSUE THREAD

**Issue by Sciss** [mgarin/weblaf#222]
I wonder if there is special reasoning for CheckBox and RadioButton having a "blurry" border style, different from all the other widgets. Personally I find it confusing, it really stands out and alludes to the buttons having a focus ring or something. Why would they not have a thin and sharp border like TextField, Button, ComboBox etc.?

**Comment by daWoife** [comment]
Hi, you are right, I also realized that.
It should be possible to switch off the shade.
The reason for this is a missing drawShade flag in class WebCheckboxUI.
There should be such a flag and a setter and getter method for it.
I will provide a commit for that the next days.

**Comment by mgarin** [comment]
Non-1px-border was chosen for these two specific components because they are different from other WebLaF border usage cases. They are small and they are icon-based. Thick border was an intended change to emphasize their icons which are smaller than anything else in the L&F.

Here is an example screenshot with both cases for check/radio:

- With current 1.5 px border
![image](https://cloud.githubusercontent.com/assets/2361389/5980312/998eb9f8-a8c8-11e4-88fb-4d7d4798790f.png)

- With 1 px border
![image](https://cloud.githubusercontent.com/assets/2361389/5980363/2b58cdd8-a8c9-11e4-8407-810f063bdc91.png)

It might be a good change (not yet sure) to reduce radiobutton border back to 1px (due to its blurriness since it is basically oval on its own) but checkbox seems to be looking worse than with thick border.

What do you think about it?

**Comment by daWoife** [comment]
Hi Mikle, so I was wrong with the shade. All components with borders have a border shade currently, isn't it ? Either with the focus color or with the shade color, and both allways with the same width. So this isnt't the difference you see currently between the borders of a textfield and checkbox or radiobutton, it's just the width of the stroke used to draw the border.
I understand your idea of making the border of a checkbox or radiobutton a bit thicker because they are so small and different to the other controls, but this is only if someone uses your standard size of these two controls. I set my checkboxes to a width and height of 25, so they are similar to the size of a normal textfield, and so they should look so too. 
So I think the best way to solve this problem would be to have a new flag like thickBorder or so and a setter and getter for this flag, so everybody can decide for his own that kind of border he wants to have for these two controls.

**Comment by Sciss** [comment]
I do think the thinner/sharp borders look more consistent. It is less apparent from the demo where they appear separated, but when you have them among other widgets, they really look different. Like daWolfe said, perhaps it could be a global preferences that one could set.

**Comment by mgarin** [comment]
It might indeed be fine if you resize those to fit other components size (like fields), but I actually never resize them in that way - large check/radio icons look unnatural.

Anyway, I'll simply make it optional, that should do the trick.

**Comment by daWoife** [comment]
You are right, in most cases. But, for example, if you have a table with a checkbox in the first column and some textfields and comboboxes in the next columns it looks rather unnatural if they are too small in comparison with the other fields. So its good that it is possibly to resize them, and also to set the width of their border.
I think its a simple change, the UI classes even need no setter and getter as I mentioned above, because normaly you want to have your checkboxes and radiobuttons look the same in your hole appplication. So it would be enouth to simply replace WebCheckBoxStyle.borderStroke with a boolean if the border should be thick or not.

**Comment by mgarin** [comment]
Possibility to alter individual components styling across the application is one of general features of WebLaF I am actually trying to maintain. You might indeed want to keep components indentical in general, but what I found after working with lots of Swing applications is that there is always some case when modified component fits better.

**Comment by daWoife** [comment]
Hi Mikle, I created a new branch BorderStyleEnum for this issue in my weblaf copy with some commits to solve this. It would be nice if you take a look, because I dit something new here, I created a enum subclass of StyleConstants and I don't know if you like that. :-)
I think its a good idea to group all enum classes together which are related to style settings. A good canditate for me to become the next enum sublass in StyleConstants would be ToolbarStyle for example. Of course it would be also possible to group the enum classes together in a new class like StyleTypes in the same directory as StyleConstants.
So what do you think about all that, and should I make a pull request or better delete my branch. :-)

**Comment by mgarin** [comment]
Just a small note - this problem will be completely gone with the new release.
Basically borders are the same now and you can also modify it in the style.
