### ISSUE TITLE
Updating title on WebDocumentPane

### ISSUE THREAD

**Issue by Chorro** [mgarin/weblaf#235]
Hi!

I'm doing a text editor and I'm using WebDocumentPane, when I open a new document (DocumentData class) its title name is "untitle" but when the user save the document the program would update the title, however it's not working.

my code:

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Text File (*.txt)", "txt"));
        fileChooser.setAcceptAllFileFilterUsed(false);

        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {

            String path = "";
            String id_title = "";

            if (! fileChooser.getSelectedFile().getName().matches("(.+)\\.txt")) {
                path = fileChooser.getSelectedFile().getAbsolutePath() + ".txt";
                id_title = fileChooser.getSelectedFile().getName() + ".txt";
            }else {
                path = fileChooser.getSelectedFile().getAbsolutePath();
                id_title = fileChooser.getSelectedFile().getName();
            }

            try {
                PrintWriter pw = new PrintWriter(new FileWriter(new File(path)));

                // Get untitled document
                DocumentData document = this.getSelectedDocument();
                // Update title and id
                document.setTitle(id_title);
                document.setId(id_title);
                pw.print(((WebEditorPane) ((WebScrollPane) document.getComponent()).getViewport().getView()).getText());
                pw.close();

            } catch (IOException e) {
                e.printStackTrace();
            }
        
a lot of thanks!

**Comment by mgarin** [comment]
First of all - I strongly recommend you not to change document's ID while it is opened in `WebDocumentPane`. `DocumentData` ID is designed to be constant while document is opened. It isn't referenced directly anywhere inside the code of `WebDocumentPane` so generally that might be a safe operation, but still I don't recommend to change it.

Next important thing - which WebLaF version are you using? 
I made a lot of changes to `WebDocumentPane` since v1.28 release and those changes addressed this issue and some others as well. All the changes can be found in sources here or in v1.29 pre-release artifacts on the site: http://weblookandfeel.com/downloads/prerelease/
With this version title should be updated properly if you simply change it in `DocumentData` object.

**Comment by Chorro** [comment]
Hello again!

thanks a lot of for your support and help. I was using WebLaF 1.28, but with 1.29 and your explanation I fix my problems.

Thanks!

**Comment by mgarin** [comment]
Good to hear :)
Will close this this issue then.
