### ISSUE TITLE
JPopupMenu not correctly visible outside of WebFrame

### ISSUE THREAD

**Issue by ClaasJG** [mgarin/weblaf#269]
This may be related to: https://github.com/mgarin/weblaf/issues/72

I am not sure if I have the same problem  but at least I have the same symptoms.
![case2](https://cloud.githubusercontent.com/assets/5501081/7213080/1fab8394-e574-11e4-86af-1e3c0b97e0bf.png)  ![case3](https://cloud.githubusercontent.com/assets/5501081/7213176/1869fda2-e576-11e4-825e-34a071f3ea8c.png)
This happens sometimes when the menu ranges out of the frame or touches the border.

And I have some render issus: (JOptionPane.showInputDialog(XXX))
![case1](https://cloud.githubusercontent.com/assets/5501081/7213100/7939f512-e574-11e4-8253-cfd943c4924f.PNG)

The blue color you can see is actualy my desktop background.

I am running WebLAF 1.28 on win 7 using jre1.8.0_31

-ClaasJG

**Comment by mgarin** [comment]
Could you try out the pre-release v1.29 binaries?
You can find them here: http://weblookandfeel.com/downloads/prerelease/
I have made a lot of changes since v1.28 including some related to window transparency.

If it doesn't help - I have a few additional questions:

1. I noticed that window on your screenshot has a simplified (old-styled) decoration - what window decoration settings do you have exactly in your win 7 system?

2. `JOptionPane` rendering issues appear instantly when displayed? It never paints properly afterwards? Does it throw any exceptions?

3. Does this code help to solve some these issues? 
`ProprietaryUtils.setWindowTransparencyAllowed ( false );`
I suggest trying this with v1.29 pre-release version as well.

**Comment by ClaasJG** [comment]
1. I am using 'windows 7 classic' but the behavior is the same with every other theme
2. The JOptionPane works fine with 1.29. In 1.28 the issues appear instantly and it never changes, nor shows any exception.
3. No, it seems to make no difference.

But I noticed that the 1.29 demo application works for me flawless.
(https://gist.github.com/ClaasJG/1330c9c2f482da2ff367 works also)
And in the moment I don't know why the application shows the bug.
So while the JOptionPane thing seems to be a bug with WebLaF, the dialog thing seems to be my fault even if I don't know why. So I guess this can be closed but I will write here again if I know why my application shows the bug and I know how to fix it, maybe somebody else stumbles over the same problem.

-ClaasJG 
Wishes a nice day

**Comment by mgarin** [comment]
Actually v1.28 is a pretty old version already and it has a few major flaws, including issues with per-pixel transparent windows, so it isn't a surprise that a lot of stuff works better in v1.29. It also had a lot of memory leak fixes and performance improvements.

Also I am aware of menu staying lightweight when it exceeds window bounds (issue from the first two screenshots you have posted), though I weren't able to find the source of this problem so far. It seems that something is wrong with bounds calculation there.

So this issue is still valid since menu is not completely fixed yet.

**Comment by mgarin** [comment]
I will soon be merging a lot of changes from `styling` branch which includes some major fixes for transparency issues. Those should be fixing at least issue (2) and I will still have to add some additional fixes for (1) case.
