### ISSUE TITLE
Table Background is not changing after update to 1.29 pre-release

### ISSUE THREAD

**Issue by iamchathu** [mgarin/weblaf#304]
After i change 1.28 to 1.29 pre release
```java
spnTblInvoice.getViewport().setBackground(new Color(57, 66, 100));
```
is not working the background of table is set to white

**Comment by mgarin** [comment]
Probably because viewport is now non-opaque. You can workaround this by making it opaque again or making table opaque and changing its background color instead.

**Comment by iamchathu** [comment]
tried now @mgarin  but didn't worked.

**Comment by mgarin** [comment]
You can simply force table to fill viewport and set its background:
```java
    public static void main ( final String[] args )
    {
        WebLookAndFeel.install ();
        
        final String[] columns = { "1", "2", "3" };
        final String[][] data = { { "1", "2", "3" }, { "1", "2", "3" } };
        final WebTable table = new WebTable ( data, columns );
        table.setFillsViewportHeight ( true );
        table.setBackground ( new Color ( 57, 66, 100 ) );
        
        final WebScrollPane scroll = new WebScrollPane ( table );
        TestFrame.show ( scroll, 50 ).setSize ( new Dimension ( 500, 500 ) );
    }
```

**Comment by iamchathu** [comment]
I'm using JTable. Will try now thanks for the reply @mgarin

**Comment by mgarin** [comment]
Those methods come from `JTable` so it doesn't really matter :)

**Comment by iamchathu** [comment]
From this code it make the row colors also save color as background.

Previously I had Puple color for background using 
```java
spnTblInvoice.getViewport().setBackground(new Color(57, 66, 100));
```

and 
```java
table.setBackground(new java.awt.Color(236, 240, 241));
```
this code is used by netbeans to add it to scrollpane
```java
spnTblInvoice.setViewportView(tblInvoice);
```

FYI : This was working with v1.28

**Comment by mgarin** [comment]
Many things changed since v1.28 and this is probably one of the changes. Though I don't really think that this specific case is an issue - there just should be a simple and convenient way to setup scrollpane and table background colors separately to achieve any desired effect.

With v1.29 there will be a way to do that. But right now I can't really change any stuff to address this. And as I already said a few times before - I strongly recommend waiting for the v1.29 update not to do the work of styling application twice since there will be a lot of changes to styling in WebLaF.

**Comment by iamchathu** [comment]
I try to wait. Thanks @mgarin  for your great contribution towards this.

**Comment by JFSolorzano** [comment]
How long more will we have to wait?, will there be improvements in the dynamic menu? (Sorry to ask here) @mgarin

**Comment by mgarin** [comment]
I can't say exact time, but these two weeks I will be working with WebLaF a lot so I will surely finish all major changes and will merge `styling` branch into master for some initial version that can be used for testing.

About dynamic menu - I am not sure improvements you might be waiting for will be there because I don't want to delay release even more. What features exactly interest you there?

**Comment by iamchathu** [comment]
Any new update on this @mgarin ?

**Comment by mgarin** [comment]
In v1.29 you will be able to control table background through the theme.

Though I have checked what you said in the very beginning:
```java
spnTblInvoice.getViewport().setBackground(new Color(57, 66, 100));
```
This does not change the whole table background even without WebLaF.
Result of this code will be something like this:
![image](https://cloud.githubusercontent.com/assets/2361389/12294195/803a78b8-ba09-11e5-8c7c-6296732d65cb.png)
Because default cell renderers are opaque.

Basically the background of a table in scroll depends on multiple factors because it uses multiple layers to display the data and underlying styling:

1. scrollpane
2. viewport
3. table
4. table cell renderer

Cell renderer always has priority in painting over table, table has priority over viewport, viewport has priority over scrollpane. 

So for example if you set background for the viewport but your table is fully opaque and taking the whole viewport space ( option `table.setFillsViewportHeight ( true );` of the table ) - you will never see the effect of changing viewport background.

On the other hand, if you set table background but your cell renderer is opaque (which is almost always true for Swing L&Fs) - its background will be painted on top of the table background and therefore will replace it but only where cells are rendered.

In the screenshot above (default Swing table with Metal L&F) you can see that viewport background is visible because table doesn't fill the viewport (it doesn't by default) and the white background is coming from the table cell renderers, but it will change if you change the table background because renderers use the table background.

I didn't really change this whole concept a lot except that you will be able to provide each specific background value in the theme XML separately and it will be easy to understand which specific value you are modifying.

**Comment by iamchathu** [comment]
This is the output I wanted but I get did not get this output.

**Comment by mgarin** [comment]
And it will also be different with the release version because of the way selection will be painted by WebLaF. It will be moved from the renderer to the table background to simplify renderer creation and customization. For instance you will be able to provide any kind of renderer without being afraid of breaking table selection display.

I have already integrated similar in the tree component, list is next and then I will add similar changes into table code.

I will post here a few ways to customize the table after the final release.

**Comment by mgarin** [comment]
A small note - table now uses `AbstractDecorationPainter` as its base which properly handles background painting according to the style settings.
