### ISSUE TITLE
WebPopup does not observe window state

### ISSUE THREAD

**Issue by Sorceror** [mgarin/weblaf#315]
When after `WebPopop` creation is whole app window minimized and maximized back `WebPopup` is not shown back if it was visible before minimization (iconification).

It can be easily tested on demo app. Select `pop-over dialog` and then `directional pop-over dialog`, if demo app is now minimized and maximized back, those dialogs are not visible (but should be) and another press of `directional pop-over dialog` button close them, because they're shown again when button pressed second time.

**Comment by mgarin** [comment]
There is indeed an issue related to window state. 
I am not yet sure what causes this behavior but I will surely investigate it.

**Comment by Sorceror** [comment]
Great, thanks, let me know if you find out the reason.

**Comment by Sorceror** [comment]
Any news with this particular issue?

**Comment by mgarin** [comment]
I have found and fixed this issue in the `styling` branch, but due to the delay with its "release" I have updated pre-release artifacts with the same changes just now, you can try updated version from here:
http://weblookandfeel.com/downloads/prerelease/

**Comment by mgarin** [comment]
Closing this as it was fixed in `styling` branch which contains all the changes coming in 1.2.9 release.
You can find most recent snapshot builds of the branch on site and maven:
https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/
http://weblookandfeel.com/downloads/styling/
If issue still appears for you just reopen this issue and I will investigate it once more.
