### ISSUE TITLE
Lists demo keeps eating memory

### ISSUE THREAD

**Issue by Sciss** [mgarin/weblaf#317]
I just notice this: In the demo, when I select the "Lists" tab, I can see in the memory status field in the bottom right corner, that the application continuously eats memory, like 60 MB per second. After it hits the GC threshold, it seems that it's mostly freed again, but it indicates that a heavy process is running, although there is no animation or such.

**Comment by mgarin** [comment]
There are a few background tasks which are working in demo and temporary consume a lot of memory. Though the demo itself is outdated - I will be replacing it with a completely different version later on and I will avoid adding such background tasks there so that demo represents real memory usage by the UI itself.

**Comment by mgarin** [comment]
That was actually happening due to older thumbnails generator. It was fixed a while ago and shouldn't happen anymore in newer library versions.
