### ISSUE TITLE
How to use WebDocumentPane

### ISSUE THREAD

**Issue by greg6614** [mgarin/weblaf#329]
Hi, I'm looking for how to use WebDocumentPane because when I use the code that you've posted in the section "How to use WebDocumentPane" and when I replace with my own document, nothing appear in the WebDocumentPane so I just would like know how to view PDF in WebDocumentPane (or may be I've misunderstanding their principles)

Thx in advance and sorry for my english, this isn't my native language.

**Comment by mgarin** [comment]
Could you provide the exact code that doesn't work for you?

**Comment by greg6614** [comment]
Yes here's the code that doesn't work for me :

public class DocumentPaneTest
{
    public static void main ( final String[] args )
    {
        WebLookAndFeel.install ();

        final WebDocumentPane pane = new WebDocumentPane ();

        final ImageIcon icon = WebLookAndFeel.getIcon ( 16 );
        pane.openDocument ( new DocumentData ( "C:/Users/Greg/doc.pdf", icon, "PDF", Color.WHITE, new WebLabel () ) );
        pane.setPreferredSize ( new Dimension ( 500, 400 ) );
        TestFrame.show ( pane );
    }
}

**Comment by mgarin** [comment]
This code works completely fine for me.
Try this code with v1.29 prerelease version - it is much more stable and polished:
http://weblookandfeel.com/downloads/prerelease/

Most probably in older v1.28 this component wasn't completed or has some major issues.

**Comment by greg6614** [comment]
You're able to see PDF document inside DocumentPane with this code ?
I think I've already try with v1.29 but I'll try another time and come back.

**Comment by mgarin** [comment]
> You're able to see PDF document inside DocumentPane with this code ?

I am able to see opened tab with empty content and this is the right behavior for the provided code.
Tab looks empty because you have added an empty label inside - `new WebLabel ()`.

I think you have misunderstood the purpose of `WebDocumentPane` - it is simply an extension for default swing `JTabbedPane` that allows you to manage tabs with ease (using IDs or document objects instead of indices) and also have multiple tabbed areas splitted on the same screen.

On its own `WebDocumentPane` doesn't provide any options to view actual documents of any format - would it be PDF, office or any other type of documents. There are plenty 3rd-party libraries which allow you to do that inside of Java applications and, to be honest, preview of such documents have nothing to do with Java L&F so I doubt there will ever be such functionality within WebLaF. But you can always use 3rd-party libraries to provide you with Swing viewer component which you can place inside the `WebDocumentPane` to achieve the desired behavior.

**Comment by mgarin** [comment]
To ensure - this is what I see launching this example:
![image](https://cloud.githubusercontent.com/assets/2361389/9467345/ae984152-4b43-11e5-86de-65fe72f3fba0.png)
And this is completely correct behavior.

This line:
`new DocumentData ( "C:/Users/Greg/doc.pdf", icon, "PDF", Color.WHITE, new WebLabel () )`
creates a data object with next parameters:
id = "C:/Users/Greg/doc.pdf" - tab ID
icon = icon - tab title icon
title = "PDF" - tab title text
background = Color.WHITE - tab background
component = new WebLabel () - tab content component

**Comment by greg6614** [comment]
It was what I thought, I have misunderstood the purpose of WebDocumentPane, so what I'm seeing is the same thing that you.
Thx for the 3rd-party libraries I'm gonna take a look.

**Comment by mgarin** [comment]
Glad that information was helpful :)
