### ISSUE TITLE
Styling problem with foreground color of option-pane and file-chooser tiles views

### ISSUE THREAD

**Issue by Sciss** [mgarin/weblaf#367]
This problem is not visible with the default skin, because here the label colour is black. To see the problem, one has to
- edit `label.xml` (in the IDE, before running style-editor) and change foreground colour for example to `red`.
- then launch `StyleEditor`. All labels are red, but when opening the `OptionPane` or `FileChooser`, text is still shown in black.
- now edit, inside the style-editor, the foreground color of `label`, for example changing to `blue`.
- thereby, all components get updated, and both option-pane and file-chooser now use the blue color.

**Comment by mgarin** [comment]
Thanks for the report and reproduction steps!

Most probably these problems are caused by difference between settings provided in style XML and initial settings provided through the code by either WebLaF or default UIs.

**Comment by Sciss** [comment]
The option-pane problem is caused by by method `configureMessageLabel` in `javax.swing.plaf.basic.BasicOptionPaneUI`. A work-around for the dark skin is this:

    UIManager.put("OptionPane.messageForeground", new ColorUIResource(216, 220, 224));

The file-chooser problem is fixed in 483b81a091e72a5655d918aa06cf9d7dff76008a

**Comment by mgarin** [comment]
This issue and some similar ones in other components are generally quite tricky. Mostly because a lot of methods like `configureMessageLabel` are private and there is no way to make them do what you want them to do. Also in many cases even methods which are using such private implementations are also private which makes it even harder to modify anyhow.

I made quite a few changes to fix this issue and replace some old bad code along the way as well - I have overridden some of the `BasicOptionPaneUI` methods to avoid `configureMessageLabel` usage and to slightly enhance the way the whole option pane layout is built. Basically all methods creating option pane content are custom now.

I have also updated option pane style, now it includes child styles for all of its elements:
```xml
<skin>

    <!-- com.alee.laf.optionpane.WebOptionPane -->

    <!-- Option pane -->
    <style type="optionpane" padding="15,15,15,15">
        <component>
            <background>237,237,237</background>
        </component>
        <painter />

        <!-- Message area -->
        <style type="panel" id="message-area" extends="transparent">

            <!-- Icon label -->
            <style type="label" id="message-icon" extends="icon" />

            <!-- Separator and message area -->
            <style type="panel" id="real-body" extends="transparent">

                <!-- Separator between icon and message -->
                <style type="panel" id="separator" extends="transparent">
                    <component>
                        <preferredSize>15,1</preferredSize>
                    </component>
                </style>

                <!-- Message area -->
                <style type="panel" id="body" extends="transparent">

                    <!-- Message labels -->
                    <style type="label" id="message" />

                </style>

            </style>

        </style>

        <!-- Buttons area -->
        <style type="panel" id="button-area" extends="transparent" padding="6,0,0,0">

            <!-- Buttons -->
            <style type="button" id="button" padding="2,10,2,10" />
            <style type="button" id="yes" extends="button" />
            <style type="button" id="no" extends="button" />
            <style type="button" id="ok" extends="button" />
            <style type="button" id="cancel" extends="button" />

        </style>

    </style>

    <!-- WebLaF-decorated information dialog -->
    <style type="rootpane" id="information" extends="dialog-decorated" />

    <!-- WebLaF-decorated error dialog -->
    <style type="rootpane" id="error" extends="dialog-decorated" />

    <!-- WebLaF-decorated question dialog -->
    <style type="rootpane" id="question" extends="dialog-decorated" />

    <!-- WebLaF-decorated warning dialog -->
    <style type="rootpane" id="warning" extends="dialog-decorated" />

</skin>
```
You can override those styles to affect option pane containers, icon and message labels directly instead of modifying global styles or creating some additional hacks for that.

Also note that if you provide any custom component into option pane it is still up to you to style that custom component, option pane itself will not change provided component style, even if it is a `JLabel`-type component.

The downside of these changes - you will probably need to update your custom styles to match the new structure of the `optionpane` style if you had any buttons re-styled in your variant since those have been moved inside the `button-area` style.

---

These changes are not yet available since they are heavily intersecting with some other major local changes I've made over November and December, but I will try to push them as soon as possible.

I will post an additional update here as soon as these changes are available.

**Comment by mgarin** [comment]
Changes I have described earlier are now available in `styling` branch.
This should fix all general styling problems for option panes :)
