### ISSUE TITLE
Non Transparent Shadow around JForm: complete-1.29 version

### ISSUE THREAD

**Issue by abdllh-fsl** [mgarin/weblaf#378]
The demo output is alright (no non-transparency issue) with java1.7.0_17. 
![untitled2](https://cloud.githubusercontent.com/assets/18183084/14975297/11a53102-1122-11e6-8608-199d2ff876f8.PNG)

But I am developing on jdk version jdk1.8.0_91 and jre1.8.0_91 and I am getting non-transparent border around JForm in GUI.
![untitled](https://cloud.githubusercontent.com/assets/18183084/14975311/3106099a-1122-11e6-9fbf-9a48b33f12df.png)

**Comment by mgarin** [comment]
By looking at the screenshot I could only say that frame/dialog opaque was not set to `false` (or was set back to `true` after) which caused the issue you can see. That might happen because of multiple things one of which is setting the background of frame/dialog directly - if you do that on any JDK8+ it might change the opaque value depending on the color.

**Comment by abdllh-fsl** [comment]
I only used the following lines of code to set webLaF:

`WebLookAndFeel.install();
WebLookAndFeel.setDecorateAllWindows(true);`

in try-catch block before my showing the ui by- 
'new TestMyUI().setVisible(this);'

**Comment by mgarin** [comment]
> Edit: After looking at the propertise from palette, I can see the opaque of my JFrame in UI is checked so it is set to true. You are pointing at that, right?

Yes, it should be set to `false` to avoid the visual effect you are experiencing.

**Comment by mgarin** [comment]
Also in newer version of L&F (from `styling` branch) you might want to use frame style directly instead of changing the static variable. It would look like this:
```java
final WebFrame frame = new WebFrame ( StyleId.frameDecorated );
```
instead of older version:
```java
WebLookAndFeel.setDecorateAllWindows ( true );
final WebFrame frame = new WebFrame ();
```
or Swing version:
```java
JFrame.setDefaultLookAndFeelDecorated ( true );
final WebFrame frame = new WebFrame ();
```
Same for the dialog. Pretty much in `styling` branch version styles take over most of visual settings in every component including windows.

**Comment by mgarin** [comment]
Were you able to solve the decoration issue?

If not - could you provide an exact code example of the frame that represents this issue?
Also, which version of WebLaF did you use? It might be important when it comes to decoration

**Comment by mgarin** [comment]
I have pushed a big chunk of changes for the decoration setup code a while ago into `styling` branch, so this should not happen anymore with newer versions. If there will still be some issues - feel free to reopen this ticket, I will investigate them.

**Comment by abdllh-fsl** [comment]
I am extremely sorry I could not be active on my issue here as I got too busy with various tasks and could not find time to work on this one. And I am glad to know there is changes you have made in current release. I will surely inform you about any issue or particularly about this one if I face with your most recent releases. Till than, thanks a lot and sorry again.
