### ISSUE TITLE
Unable to set window decorations

### ISSUE THREAD

**Issue by RobertBColton** [mgarin/weblaf#388]
This occurs with the snapshot build from yesterday and the snapshot build from before that with 1.29, this does not occur in 1.28.

With the following code, windows do not have any decoration, not the native one or the one provided by the look and feel:

```java
        JFrame.setDefaultLookAndFeelDecorated(true);
        JDialog.setDefaultLookAndFeelDecorated(true);
```

Following the advice of this stackoverflow post, I also can not change the decorations at runtime, which I am able to do under Nimbus, Swing, and the native Win32/Gtk look and feels.
http://stackoverflow.com/a/17262722/2734025

```java
contentPane.getRootPane().setWindowDecorationStyle(JRootPane.FRAME);
```

The following exception is encountered.
```
Populate bindings
AWT-EventQueue-0: 
java.lang.RuntimeException: Unable to modify window decoration while it is displayed
	at com.alee.laf.rootpane.WebRootPaneUI.updateWindowDecorations(WebRootPaneUI.java:445)
	at com.alee.laf.rootpane.WebRootPaneUI.propertyChange(WebRootPaneUI.java:429)
	at java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.awt.Component.firePropertyChange(Unknown Source)
	at javax.swing.JComponent.firePropertyChange(Unknown Source)
	at javax.swing.JRootPane.setWindowDecorationStyle(Unknown Source)
	at org.lateralgm.main.LGM.applyPreferences(LGM.java:2025)
```

**Comment by mgarin** [comment]
About the `setDefaultLookAndFeelDecorated` methods - I am already looking into that and might have a solution soon. I have temporary changed decoration behavior in the `styling` branch towards using the styles instead of a global setting which makes a lot more sense, but I will be adding backward compatibility for `setDefaultLookAndFeelDecorated` setting as well.

Pretty much what you need to decorate `WebFrame` with WebLaF is:
```java
WebFrame frame = new WebFrame ( StyleId.frameDecorated );
```
And no weird global constants needed. 
Same for common `JFrame` with no WebLaF code:
```java
JFrame frame = new JFrame();
frame.getRootPane ().putClientProperty ( "styleId", "frame-decorated" );
```
That is also just a tip of the iceberg - you can easily customize frame decoration through styles however you like and provide your custom style for each specific frame/dialog instance.

---

Now to the second issue - 

> Following the advice of this stackoverflow post, I also can not change the decorations at runtime, which I am able to do under Nimbus, Swing, and the native Win32/Gtk look and feels.

Even though you can adjust the decoration of root pane in runtime, you cannot undecorated or decorate frame/dialog after it became visible. Here is a simple example so you could understand what I mean:
```java
public class DecorationExample
{
    public static void main ( final String[] args )
    {
        final JFrame f = new JFrame ();
        final JButton button = new JButton ( "test" );
        button.addActionListener ( new ActionListener ()
        {
            @Override
            public void actionPerformed ( final ActionEvent e )
            {
                f.getRootPane ().setWindowDecorationStyle ( JRootPane.FRAME );
                f.setUndecorated ( true );
            }
        } );
        f.add ( button );
        f.setSize ( 500, 500 );
        f.setLocationRelativeTo ( null );
        f.setVisible ( true );
    }
}
```
This is pretty much how a code changing from native frame decoration to Metal one would look like. But on the line `f.setUndecorated ( true );` you will get next exception:
```
Exception in thread "AWT-EventQueue-0" java.awt.IllegalComponentStateException: The frame is displayable.
```
That is because you cannot show/hide native decoration in runtime.
And if you remove that line and try running the code you will see this:
![image](https://cloud.githubusercontent.com/assets/2361389/15316236/bae6153a-1c24-11e6-861a-e12649163cc9.png)
Yes, decoration got installed properly, but native decoration is still there and not going anywhere.

It is true though that if the frame is undecorated from the start you can switch between custom decorations as much as you like since it is all painted using common Swing means. I will be adding a small fix for that, but for the rest of the cases you will still see the same exception:
```
java.lang.RuntimeException: Unable to modify window decoration while it is displayed
```

**Comment by mgarin** [comment]
I have finally managed to create a compromise solution for all possible use cases (there are around 12 possible cases how frame/dialog decoration could be initialized). 

I have already pushed all changes into Git: https://github.com/mgarin/weblaf/commit/98a2d80189ff8f8593f326aa7173c20538c31a65

Updated snapshot builds are also available now with this fix included:
http://weblookandfeel.com/downloads/styling/
https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/

**Comment by RobertBColton** [comment]
I can say it does seem to be resolved, the decorations are showing, but I am having a bit of trouble with the snapshot as it is being rather laggy. I've also noticed that the complete jar has gone from 5.9mb's to 11mb's. Is this intentional?
http://weblookandfeel.com/downloads/styling/

**Comment by Sciss** [comment]
@RobertBColton by "laggy" you mean that the components paint rather slowly, right? I have also noticed that component painting is much slower than it was in the 1.28 version. Probably at one point one has to do a bit of profiling to see why things are slow. I have the feeling (from seeing it occasional) that some painting code is run excessively (like three, four, five times) when changing a single property or initialising. Also things like changing decorations (focus on/off) takes rather long.

**Comment by RobertBColton** [comment]
Yes I would say so, but more so the last thing you said about changing the state. Specifically when the frame is first showing it's even slower with the borders. But the main thing was that it caused the Window to go offscreen and out of bounds where I could not get it back on restart (the main frame bounds are saved in Java preferences; I cleared that to get it back).

**Comment by mgarin** [comment]
> I've also noticed that the complete jar has gone from 5.9mb's to 11.6mb's. Is this intentional?

That is an old issue of the FTP client I am using to upload stuff. 
Fixed it now, size should be back to 5.9 mb.

> the decorations are showing, but I am having a bit of trouble with the snapshot as it is being rather laggy

> I have the feeling (from seeing it occasionally) that some painting code is run excessively (like three, four, five times) when changing a single property or initialising. Also things like changing decorations (focus on/off) takes rather long.

Current styling system is times more complicated than old simple UI implementations running static painting code. It certainly takes a lot more time to initialize, but in runtime it should perform almost as well as the previous UI implementations.

Though I am sure there could still be some issues and unoptimized code parts, so I have created a separate issue specifically for all performance reports - all information is there: #389

**Comment by mgarin** [comment]
@RobertBColton 

> Attempting to change it at runtime, as was shown above, I actually get some odd results. If I iconify/minimize the window to the taskbar and then reopen it, I get the following for a brief second:

How exactly do you change it in runtime?
I suppose it is a `JFrame` you are experiencing this issue with?

**Comment by RobertBColton** [comment]
Well, I actually had to modify the code, what I had before called setVisible before calling setWindowDecorationStyle. However, oddly enough, that did still work with the other look and feels.
```java
		Window[] windows = Window.getWindows();
		for (Window window : windows) {
			final boolean visible = window.isVisible();
			LookAndFeel laf = UIManager.getLookAndFeel();
			final boolean decorate = Prefs.decorateWindowBorders && laf.getSupportsWindowDecorations();
			if (window instanceof Frame && window instanceof RootPaneContainer) {
				final Frame decframe = (Frame) window;
				if (decorate != decframe.isUndecorated()) {
					SwingUtilities.invokeLater(new Runnable() {
						@Override
						public void run()
							{
							decframe.dispose();
							decframe.setShape(null);
							decframe.setUndecorated(decorate);
							((RootPaneContainer) decframe).getRootPane().setWindowDecorationStyle(decorate ? JRootPane.FRAME : JRootPane.NONE);
							decframe.setVisible(visible);
							}
					});
				}
			} else if (window instanceof Dialog) {
				final Dialog decdialog = (Dialog) window;
				if (decorate != decdialog.isUndecorated()) {
					SwingUtilities.invokeLater(new Runnable() {
						@Override
						public void run()
							{
							decdialog.dispose();
							decdialog.setShape(null);
							decdialog.setUndecorated(decorate);
							((RootPaneContainer) decdialog).getRootPane().setWindowDecorationStyle(decorate ? JRootPane.PLAIN_DIALOG : JRootPane.NONE);
							decdialog.setVisible(visible);
							}
					});
				}
			}
		}
```

**Comment by mgarin** [comment]
> I am also not seeing borders on dialogs that extend JDialog, I see them on my dialogs where I create a JDialog though. I tested the same exact dialogs and when then extend JDialog they appear with absolutely no border when JDialog.setDefaultLookAndFeelDecorated() is true. If I create JDialog and set the layout and everything the same way as I do in the constructor, then they have a border and appear fine. This occurs without my code below and even when I run the constructor in a SwingUtilities.invokeLater() Runnable.

This was indeed an issue - only direct `JFrame` and `JDialog` instances got decorated. I have patched this up now - fix will be available in snapshot builds slightly later.

> I actually had to modify the code, what I had before called setVisible before calling setWindowDecorationStyle. However, oddly enough, that did still work with the other look and feels.

That is a good point as well, added a fix for this as well, it will also be available in snapshot builds slightly later. I have removed usage of the global setting for `JDialog` and `JFrame` (and subclasses) within the painter enabling decorations and instead added general case checks for the decoration style as it is being set anyway and it is more reliable.

Now pretty much all you need is to set the decoration style before showing the frame OR set frame undecorated and then set decoration style anytime you like, even after frame is already being shown - I have removed some unnecessary checks there as well, so it works now.

> There is still a problem with this code. setWindowDecoration style for Dialog actually needs to remember what the previous window decoration style was, because there's a flag for file choosers, warnings, errors, and other JOptionPane dialog types besides just PLAINT_DIALOG. Because of this I am bordering on requiring a restart to change the window decorations because the code is getting rather unwieldy, but I still want to document this for other people.

I have patched this up as well, painter was indeed changing decoration style to `JRootPane.FRAME` or `JRootPane.PLAIN_DIALOG`. From now on that only happens if there was no decoration style specified, but WebLaF style forces frame or dialog to become decorated.

> With the updated code it does appear to work under all look and feels, but with Web L&F I get the following exception going from L&F to native decorations. When going from native to L&F decorations, it does not occur.

How exactly do you do that?
Because you would at least need to recreate frame or dialog to get native decoration back.

**Comment by RobertBColton** [comment]
> I have patched this up as well, painter was indeed changing decoration style to JRootPane.FRAME or JRootPane.PLAIN_DIALOG.

> How exactly do you do that?

My apologies, when I said that, I meant there was a problem with my code. That big for loop I pasted above is in my applyPreferences() method which goes through all the windows and toggles their decorations when the preference changes at runtime. The problem in my code is that I don't keep the previous decoration style of Dialog anywhere, so if they do the preference twice, any open Dialogs are all set to PLAIN_DIALOG even if that's not what they were before. I would still say because of all this Java really doesn't support changing the decorations at runtime. That said, your code should be fine now and I will test later when the snapshot is updated.

**Comment by mgarin** [comment]
> My apologies, when I said that, I meant there was a problem with my code. That big for loop I pasted above is in my applyPreferences() method which goes through all the windows and toggles their decorations when the preference changes at runtime. 

Yep, I already tried running that code just a moment ago and there is indeed still an issue present when you go back to native decoration. 

That issue happens because WebLaF installs a specific style upon dialog or frame initialization (determined by many various factors) and that style doesn't go anywhere after you try to switch back to `JRootPane.NONE` decoration style. I am currently looking for whether I could provide a solution for that specific case or not.

**Comment by RobertBColton** [comment]
Ahhh, I see now. And just to mention that specific code for PLAIN_DIALOG/FRAME/NONE is from other Stack Overflow posts, it seems to be the accepted solution. Again though, this really is a big pain, it would be nice if Swing had a utility method that did this. I might perhaps suggest it as an enhancement to them, it's also something that Web L&F could consider since so many people want to be able to do it.

**Comment by mgarin** [comment]
I'm not sure that changing frame decoration in runtime is common thing.

But anyway your code example that changes frame decorations in runtime seems to be a good solution for general case and any L&F. I might add something like that in future updates for some cases like frame and dialog style change so it would correctly affect (setup/restore) decoration in runtime.

**Comment by mgarin** [comment]
I have added last changes that fixed remaining issues. I will be releasing a snapshot build soon with it and all previous fixes for the decoration.

Your code will function properly with those fixes and it shouldn't matter anymore when you provide decoration style. Though window native decoration can still only be enabled/disabled while window is not visible as this has nothing to do with WebLaF and a native/JDK limitation.

**Comment by mgarin** [comment]
You can try out the new version from here:
https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/

I didn't update artifacts on the site yet due to some issues with FTP access, I will be updating those later, probably along with some more changes in the branch.

**Comment by RobertBColton** [comment]
How do I download from there? I've been wondering that for a while actually haha. I normally use the "complete" jar and I was not able to find it in those directories.

**Comment by mgarin** [comment]
There is no complete JAR there, it is a maven snapshot repository.

You need to either attach it as a Maven dependency in your IDE project or download all separate JARs from there manually plus all the dependencies and attach all of them to your project.

**Comment by mgarin** [comment]
Complete JAR simply includes next parts:
- `weblaf-core-1.29.jar`
- `weblaf-ui-1.29.jar`
- `rsyntaxtextarea-2.5.7.jar`
- `slf4j-api-1.7.12.jar`
- `slf4j-simple-1.7.12.jar`
- `java-image-scaling-0.8.6.jar`
- `jericho-html-3.3.jar`
- `xstream-1.4.9.jar`

**Comment by mgarin** [comment]
Also, a small note on this exception:
```
java.awt.IllegalComponentStateException: The frame background color is not opaque
    at java.awt.Frame.setUndecorated(Unknown Source)
    at org.lateralgm.main.LGM$5.run(LGM.java:2025)
```
That actually happens because you are trying to make frame decorated again while its background is transparent. You didn't get this behavior with other L&F because most of them do not make the window non-opaque (which on JDK7+ means setting transparent background color) as it doesn't work properly on all existing OS and requires a lot of additional checks and workarounds, but WebLaF does that.

What you need to do to fix this is simply set any opaque color as window background:
```java
Window[] windows = Window.getWindows();
for (Window window : windows) {
    final boolean visible = window.isVisible();
    LookAndFeel laf = UIManager.getLookAndFeel();
    final boolean decorate = Prefs.decorateWindowBorders && laf.getSupportsWindowDecorations();
    if (window instanceof Frame) {
        final Frame decframe = (Frame) window;
        if (decorate != decframe.isUndecorated()) {
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run()
                    {
                    decframe.dispose();
                    decframe.setShape(null);
                    decframe.setBackground(Color.WHITE);
                    decframe.setUndecorated(decorate);
                    if (decframe instanceof RootPaneContainer)
                        ((RootPaneContainer) decframe).getRootPane().setWindowDecorationStyle(
                                decorate ? JRootPane.FRAME : JRootPane.NONE);
                    decframe.setVisible(visible);
                    }
            });
        }
    } else if (window instanceof Dialog) {
        final Dialog decdialog = (Dialog) window;
        if (decorate != decdialog.isUndecorated()) {
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run()
                    {
                    decdialog.dispose();
                    decdialog.setShape(null);
                    decdialog.setBackground(Color.WHITE);
                    decdialog.setUndecorated(decorate);
                    if (decdialog instanceof RootPaneContainer)
                        ((RootPaneContainer) decdialog).getRootPane().setWindowDecorationStyle(
                                decorate ? JRootPane.PLAIN_DIALOG : JRootPane.NONE);
                    decdialog.setVisible(visible);
                    }
            });
        }
    }
}
```
You can do it for both of the cases before you call `setUndecorated` as it doesn't matter that much. Or you can even check whether the background in the window is transparent and only then replace it with something opaque.
