### ISSUE TITLE
WebMenu problems after displaying WebNotification

### ISSUE THREAD

**Issue by T1mmos** [mgarin/weblaf#403]
Hi,

It seems, whenever you add a non-null parent to a WebNotification, the menus won't always show up after that WebNotification has disappeared.

Here is a test program:

`	

    package demo;

	import java.awt.Dimension;
	import java.awt.event.ActionEvent;

	import javax.swing.AbstractAction;
	import javax.swing.Action;
	import javax.swing.SwingUtilities;

	import com.alee.laf.WebLookAndFeel;
	import com.alee.laf.menu.WebMenu;
	import com.alee.laf.menu.WebMenuBar;
	import com.alee.laf.menu.WebMenuItem;
	import com.alee.laf.rootpane.WebFrame;
	import com.alee.managers.notification.NotificationManager;
	import com.alee.managers.notification.WebNotification;

	public class Test {

		private static String TITLE_MENU = "Notifcations";
		private static String TITLE_OK    = "No problem here!";
		private static String TITLE_PROBLEM = "Click And Kill That Menu!";
		private static String MSG_OK        = "If you never clicked \""+TITLE_PROBLEM+"\" before, you won't see problems with the menu bar";
		private static String MSG_PROBLEM = "When this notification has disappeared, the menus will not always show up when clicking \""+TITLE_MENU+"\"!";

		public static void main(String[] args) {
			WebLookAndFeel.install();
			SwingUtilities.invokeLater(new Runnable() {

				@Override
				public void run() {
					WebFrame frame = new WebFrame();

					WebMenuBar bar = new WebMenuBar();
					WebMenu menu1 = new WebMenu(TITLE_MENU);
					WebMenuItem item1 = new WebMenuItem(getNotifAction(TITLE_OK, MSG_OK, null));
					WebMenuItem item2 = new WebMenuItem(getNotifAction(TITLE_PROBLEM, MSG_PROBLEM, frame));
					menu1.add(item1);
					menu1.add(item2);
					bar.add(menu1);

					frame.setJMenuBar(bar);

					frame.setMinimumSize(new Dimension(300, 200));
					frame.pack();
					frame.setLocationRelativeTo(null);
					frame.setVisible(true);
				}
			});
		}

		public static Action getNotifAction(String title, final String msg, final WebFrame frame) {
			return new AbstractAction(title) {

				@Override
				public void actionPerformed(ActionEvent e) {
					WebNotification notif = new WebNotification();
					notif.setDisplayTime(5000);
					notif.setContent(msg);
					NotificationManager.showNotification(frame, notif);
				}
			};
		}
	}
`

It's indeterministic: sometimes you can click the menu and the content appears, but sometimes the menu title appears clicked but the content isn't showing - so you can't pick a menu item. 

Apparently I don't have issues when using a Web**Inner**Notification.

**Comment by mgarin** [comment]
Thanks for reporting this one and for the example!
I will surely investigate this issue and will come back with more information.

**Comment by mgarin** [comment]
I have tried this example and I cannot really reproduce the issue on current v1.2.9 build from the `styling` branch, but it seems that you are using an older version - either v1.28 or v1.29 pre-styling - due to `WebFrame` being located in `com.alee.laf.rootpane` package. Those versions indeed had the issue you have mentioned here but it was fixed quite a while ago.

I would recommend you to try out the newest v1.2.9 build from either of the sources:
https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/
http://weblookandfeel.com/downloads/styling/
to see if you can still reproduce this issue or not.

If you would have any other problems with that version - simply throw them as an issue here and I will do my best to fix them as quick as possible.

**Comment by T1mmos** [comment]
OK, seems it is indeed solved in the latest build(s). 

Just a question: some methods and even full classes have disappeared now, e.g. there is no longer a WebButtonGroup of a method in WebButton called "setRolloverDecoratedOnly". Are these intended changes or am I missing a part of the API?

Btw, I like the subtile UI changes e.g. a thinner blue line around a focused component.

**Comment by mgarin** [comment]
Glad it was fixed :)

> Just a question: some methods and even full classes have disappeared now, e.g. there is no longer a WebButtonGroup of a method in WebButton called "setRolloverDecoratedOnly". Are these intended changes or am I missing a part of the API?

These are intended changes and just a tip of an iceberg of overall changes I've made across the code. Next release already includes more changes than library had overall since the beginning and until v1.28 release.

Also, I did not remove any functionality without providing a replacement, though some of the replacements might not be obvious at all.

`WebButtonGroup` was too specific and worked only for buttons - I didn't like that and that is why it was replaced by a `GroupPane` container that can visually group pretty much any UI elements now. It might be pointless to group some of the UI elements which do not have a bordered style, but that should be quite obvious. Here is an example of a button, textfield and combobox being grouped together:
![image](https://cloud.githubusercontent.com/assets/2361389/18012173/06a3000a-6bc1-11e6-9f54-6527313d01fd.png)

Regarding the second change you mentioned with `WebButton` method - all decoration-related methods have been removed from the components API as they are only creating a mess in the application code where you use them. A proper way of styling all of the existing components have been introduced instead which moves all the settings related to the components style into separate skins, based on XML files with a custom structure.

Quite a while ago I have posted an introduction wiki article for the new styling system:
https://github.com/mgarin/weblaf/wiki/Styling-introduction
It is a bit outdated due to some changes, but it is still worth reading as it will give you a general idea of how styling works in WebLaF now.

You can also grasp the scale of the existing skins (light and dark so far) by looking at the skin sources:
https://github.com/mgarin/weblaf/tree/styling/modules/ui/src/com/alee/skin/web/resources
https://github.com/mgarin/weblaf/tree/styling/modules/ui/src/com/alee/skin/dark/resources

Here is an example of multiple button styles put together in one file:
https://github.com/mgarin/weblaf/blob/styling/modules/ui/src/com/alee/skin/web/resources/button.xml

Obviously, you can now do anything you want with those - slightly change or completely rewrite all of the styles, add new ones, conveniently split styles into extensions for your plugins etc.

**Comment by mgarin** [comment]
If there any any other things which are missing and you cannot find the replacement - feel free to ask, I will save your time searching for it.

Also you can join WebLaF room on Gitter: https://gitter.im/mgarin/weblaf - it might be much more convenient to ask your question there than creating a new issue every time, unless you found a bug or want to post a request of course :)
