### ISSUE TITLE
Duplicate dependencies in pom.xml

### ISSUE THREAD

**Issue by rvillablanca** [mgarin/weblaf#405]
There are duplicate dependency versions of SLF4J. The warning thrown out is:

`
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.alee:weblaf:jar:1.28
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.slf4j:slf4j-api:jar -> duplicate declaration of version 1.7.7 @ line 107, column 21
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.slf4j:slf4j-simple:jar -> duplicate declaration of version 1.7.7 @ line 112, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
`

**Comment by mgarin** [comment]
If you meant `pom.xml` from the current main branch:
https://github.com/mgarin/weblaf/blob/master/build/pom.xml
then it is a deprecated one and will be completely replaced with a new one along with the v1.2.9 release.

You can look at the new `pom.xml` in the `styling` branch:
https://github.com/mgarin/weblaf/blob/styling/pom.xml
https://github.com/mgarin/weblaf/blob/styling/modules/core/pom.xml
https://github.com/mgarin/weblaf/blob/styling/modules/ui/pom.xml
https://github.com/mgarin/weblaf/blob/styling/modules/demo/pom.xml

Those are used to build SNAPSHOT artifacts of the v1.2.9 version which you can find here:
https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/

By the way, I do recommend you to use either of these instead of v1.28 version:

Site version - older pre-styling v.1.2.9 build:
http://weblookandfeel.com/download/
This is an older quite stable version without major changes introduced in `styling` branch. This might still be useful for software release cases.

Most recent - `styling` branch build:
https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/
http://weblookandfeel.com/downloads/styling/
This is the most recent up-to-date version that includes lots of API and internal changes. I do recommend using it in case you are working on a project that is not yet to be released so you won't have to switch to new APIs later on. That version also provides a full access to components styling and contains a few new components like docking framework. It is still not fully finished, but I am actively working on it and trying to keep it as bug-free as it is possible by fixing any appearing issues straight away.

**Comment by mgarin** [comment]
I will close this one as it should be solved with the next update :)
