### ISSUE TITLE
Default JLabel tooltip should be white for HTML text

### ISSUE THREAD

**Issue by fjoncourt** [mgarin/weblaf#420]
Hi,

With release 1.28 
```
label.setToolTipText("<html><i>Set the source port to use for sending the SPA packet</i></html>")
```
looks like that:
![html_tooltip 1 28](https://cloud.githubusercontent.com/assets/3234923/20058093/73752d86-a4ef-11e6-9f52-1806e4adb92b.png)

With release 1.29 the text is hidden:
![html_tooltip 1 29](https://cloud.githubusercontent.com/assets/3234923/20058097/76f7b500-a4ef-11e6-9e44-df65941bbe4d.png)

But using
```
<html><font color=orange><i>Send the SPA packet over a randomly assigned port</i></font></html>
```
it displays:
![html_tooltip_with_font_color 1 29](https://cloud.githubusercontent.com/assets/3234923/20058104/8077ea64-a4ef-11e6-9bdb-36480b2cd609.png)

Could you set the default font color for embedded html to white so that we can see the text :)

Regards,

**Comment by mgarin** [comment]
This issue indeed exists and it didn't appear in previous versions because of the specifics of `HTMLDocument` creation for Swing components that use HTML.

Pretty much what happens is when component detects HTML content within its own text it generates a special `View` used to paint the HTML content later. Class `BasicHTML` is used to generate and update that `View` on demand and component foreground is hardcoded to be the default `color` property for the `<body>` tag there.

Previously (in v1.28 and earlier) it worked just fine because WebLaF was still using `foreground` color to paint labels, buttons, tooltips and other similar components text content, but since v1.2.9 that is not the case anymore. Styling system relies on its own settings provided in the styles and would only take custom foregrounds when it is provided by developer explicitly. By default it uses its own colors and, obviously, it is different for some components than their default `foreground` value which is still used for the HTML rendering hardcoded in `BasicHTML`.

I am still not sure how I will fix this problem and I am trying some different approaches right now. Either way I will have to fix it as it also affects all other components in the same manner, it is just harder to notice because default `foreground` for labels, buttons and some other components match with the style color for their text (black).

**Comment by mgarin** [comment]
Also, generally speaking, HTML should always be your last resort as its rendering is extremely slow in Swing. For example compared to plain text - HTML could be up to 100 times slower and that is not an exaggeration.

The solution I would propose (in case you are using latest `styling` branch WebLaF builds) - use styled versions of components or, in case it is tooltip and you cannot explicitly set its style ID, override default style to use styled content for the text instead of a plain one. Let me explain what that means in details.

First of all, WebLaF in its current iteration has each unique component broken down into small pieces - either parts of decoration or contents. You can clearly see that in the style XML for any component, for example button ( taken from [this file](https://github.com/mgarin/weblaf/blob/styling/modules/ui/src/com/alee/skin/web/resources/button.xml) ):
```xml
    <style type="button" padding="2,4,2,4">
        <painter>
            <decorations>
                <decoration>
                    <WebShape round="3" />
                    <WebShadow type="outer" width="2" />
                    <LineBorder color="170,170,170" />
                    <GradientBackground>
                        <color>white</color>
                        <color>223,223,223</color>
                    </GradientBackground>
                    <ButtonLayout>
                        <ButtonIcon constraints="icon" />
                        <ButtonText constraints="text" color="black" />
                    </ButtonLayout>
                </decoration>
                <decoration states="focused">
                    <LineBorder color="85,130,190" />
                </decoration>
                <decoration states="pressed">
                    <WebShadow type="outer" opacity="0" />
                    <WebShadow type="inner" width="6" />
                    <ColorBackground color="210,210,210" />
                </decoration>
                <decoration states="disabled">
                    <WebShadow type="outer" opacity="0" />
                    <LineBorder color="lightGray" />
                    <ButtonLayout>
                        <ButtonText color="120,120,120" />
                    </ButtonLayout>
                </decoration>
            </decorations>
        </painter>
    </style>
```
You can see how component is broken down into small parts for each of its state. It has everything - shape, shadow, border, background, contents and layout - specified explicitly with their own settings. You can of course control all those settings if you want to, it was described in [this wiki article](https://github.com/mgarin/weblaf/wiki/Styling-introduction) in details.

In the button skin file you can also find the next separate style:
```xml
    <!-- Button supporting styled text -->
    <style type="button" id="styled">
        <painter>
            <decorations>
                <decoration>
                    <ButtonLayout>
                        <ButtonIcon constraints="icon" />
                        <StyledButtonText constraints="text" color="black" />
                    </ButtonLayout>
                </decoration>
                <decoration states="disabled">
                    <ButtonLayout>
                        <StyledButtonText color="120,120,120" ignoreStyleColors="true" />
                    </ButtonLayout>
                </decoration>
            </decorations>
        </painter>
    </style>
```
This is exactly the styled version of the component I was talking about. As you might see from the XML - the only different thing it uses is `StyledButtonText` instead of plain `ButtonText`. By using that specific text content implementation that style enables you to use `WebStyledLabel` component [syntax](https://github.com/mgarin/weblaf/wiki/How-to-use-WebStyledLabel#styled-text-syntax) in button!

So here is a small example:
```java
public class StyledButton
{
    public static void main ( final String[] args )
    {
        WebLookAndFeel.install ();

        final String text = "{Sample:b} {styled:c(red)} button";
        
        final WebButton styled = new WebButton ( StyleId.buttonStyled, text );

        final WebButton plain = new WebButton ( text );

        TestFrame.show ( 15, false, 15, styled, plain );
    }
}
```
And the result:

![image](https://cloud.githubusercontent.com/assets/2361389/20211560/2be62726-a810-11e6-9b9c-4903e1c9bead.png)

So the style attached to the button actually changes its text rendering behavior. 

The same trick can be applied to the tooltips and the only problem is that you cannot explicitly set tooltip style ID and you probably don't even want to. So what you need to do is override the default tooltip style which looks like this:
```java
    <style type="tooltip">
        <painter>
            <decorations>
                <decoration>
                    <WebShape round="2" />
                    <LineBorder color="black" />
                    <ColorBackground color="black" />
                    <ToolTipText padding="2,4,2,4" color="245,245,245" />
                </decoration>
            </decorations>
        </painter>
    </style>
```
With the styled version of content:
```java
    <style type="tooltip">
        <painter>
            <decorations>
                <decoration>
                    <StyledToolTipText padding="2,4,2,4" color="245,245,245" />
                </decoration>
            </decorations>
        </painter>
    </style>
```
Now all of the default tooltips will support style syntax of `WebStyledLabel` component and you can easily do most of the common things you would use HTML for:

![image](https://cloud.githubusercontent.com/assets/2361389/20215141/8a28c560-a823-11e6-9bb2-e07c4c369ec5.png)

![image](https://cloud.githubusercontent.com/assets/2361389/20215206/c2e598c4-a823-11e6-9a72-57611a6844a5.png)

This is the styled text for the second example:
```java
final String text = "{Sample:b} {styled:c(red)} button" + "\n" + "With some {hard:u} line breaks" + "\n\n" + "That easily!";
```
And this is the same text using HTML:
```java
final String text = "<html><b>Sample</b> <font color='red'>styled</font> button<br>With some <u>hard</u> line breaks<br><br>That easily!</html>";
```

To summ up - you will need to do next steps to enable styling syntax in tooltips:

1. Create custom skin for WebLaF, either fully hand-crafted or extending existing one
2. Override the default tooltip style and provide `StyledToolTipText` as shown above
3. Setup WebLaF and use your own skin as the main application skin

That might sound as a lot to do, but it is actually not. Plus you will be able to customize or create any additional styles for any components if you want to as you would already have a custom skin.

---

It is important to mention that all of the examples above are only applicable to WebLaF v1.2.9 `styling` branch builds and later releases, it would not work with any older versions.

You can find the latest `styling` builds here:
https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/

**Comment by mgarin** [comment]
Also, I have pushed a fix ( 462b375 ) for HTML within the tooltips, labels, buttons and other components - it should now properly use text color specified in the skin. 

That took quite a bit of effort and I had to make my own copy of `BasicHTML` class to change some of its behaviors. I also made a major change to how HTML `View` is now generated and cached within the component. 

I will be doing some more related changes soon, but everything should be working fine with the latest build which you can here: https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/

**Comment by fjoncourt** [comment]
> To summ up - you will need to do next steps to enable styling syntax in tooltips:
> 
>  1. Create custom skin for WebLaF, either fully hand-crafted or extending existing one
>  2. Override the default tooltip style and provide StyledToolTipText as shown above
>  3. Setup WebLaF and use your own skin as the main application skin
> 
> That might sound as a lot to do, but it is actually not. Plus you will be able to customize or create any 
>  additional styles for any components if you want to as you would already have a custom skin.

Thanks for your explanation and your quick reply/fix. It sounds great and I will definitely give it a try.

**Comment by Endogen** [comment]
Regarding the link [https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/](https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel) that you referred to. 
I would like to start [weblaf-demo-1.2.9-20161111.173007-75.jar](https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/weblaf-demo/1.2.9-SNAPSHOT/weblaf-demo-1.2.9-20161111.173007-75.jar) but i get an error `kein Hauptmanifestattribut, in weblaf-demo-1.2.9-20160914.190507-71.jar`. Something about a non existing manifest attribute. How do i fix that?

**Comment by mgarin** [comment]
@fjoncourt If you will have any questions - feel free to ask in [chat](https://gitter.im/mgarin/weblaf) or just [mail me](mailto:mgarin@alee.com) directly.

@Endogen I haven't fixed the manifest file for the maven builds of modules - those pretty much generate some default manifest without any information about the main class. If you want to run demo - you can download the fully packed version from the site: http://weblookandfeel.com/downloads/styling/

Specifically - [weblaf-demo-1.29.jar](http://weblookandfeel.com/downloads/styling/weblaf-demo-1.29.jar) - it is an artifact built with the ANT script that could be found in the project.

Be aware that builds on the site might sometimes be slightly behind the maven ones as I have to update those manually and I do not update them on every single commit to the `styling` branch. Generally if you want the most recent demo build - you can download the sources from `styling` branch and build the demo using ANT script, it has everything configured so you can run it straight away.

You can find the short guide on how to build stuff in [this article](https://github.com/mgarin/weblaf/wiki/How-to-build-WebLaF-binaries) on wiki.

**Comment by mgarin** [comment]
@Endogen I have added a separate issue #421 to make sure I will include the correct manifest information before the release. As soon as its closed - you should be able to run maven `demo` and `ui` modules artifacts as well.
