### ISSUE TITLE
How can I change the ComboBox Color?

### ISSUE THREAD

**Issue by EricCong2016** [mgarin/weblaf#425]
How can I change the ComboBox Color?

It always seem like that.The white color mixed with a little gray.
setBackground method doesn't work.
Thank you : )

**Comment by EricCong2016** [comment]
![Uploading image.png…]()
![Uploading PRZSE]422A@D6ZK%U9O]%[S.png…]()

**Comment by mgarin** [comment]
Sorry for the big delay - I was hoping to update the styling guide before providing an expanded answer, but it is taking longer than I wanted to, so I will give the answer first.

--- 

To answer your question - yes, default combobox background contains two colors - white and rgb(223,223,223). Whether or not you can change that depends on which version of WebLaF you are actually using - is it the one from the site? or one of the builds from `styling` branch? With the latter one you can actually re-style it quite easily to your liking. With the older versions it would be quite tough to do as proper styling system implementation wasn't there yet.

#### Using newest v1.2.9 `styling` branch build

Basically I would recommend using one of the `styling` branch builds if you're just starting with WebLaF and want to keep up with the latest changes and try all the new features. You can find it here:
http://weblookandfeel.com/downloads/styling/
Or on maven snapshot repository, but it only contains separated modules so you would need to get at least `core` and `ui` ones plus dependencies:
https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/
This option is easier only if you are using maven project.

Next to the styling process - it should be quite easy to understand the basics by just looking at the [existing styles](https://github.com/mgarin/weblaf/tree/styling/modules/ui/src/com/alee/skin/web/resources), but I also strongly recommend reading [this introduction article on wiki](https://github.com/mgarin/weblaf/wiki/Styling-introduction) - it is slightly outdated (missing some of the newest enhancements), but it should give you a general idea of how things work. You can also wait a bit more as I will be updating it quite soon so it will cover all aspects of styling process.

As a next step - have a look at [combobox skin](https://github.com/mgarin/weblaf/blob/styling/modules/ui/src/com/alee/skin/web/resources/combobox.xml). It contains a separate style for every combobox element - combobox itself, editor and renderer inside of it, drop-down button, popup scroll, popup list and its renderer. Background of the combobox itself is described in the main combobox style:
```xml
    <!-- Combobox -->
    <style type="combobox">
        <component>
            <opaque>false</opaque>
        </component>
        <painter>
            <decorations>
                <decoration>
                    <WebShape round="2" />
                    <WebShadow type="outer" width="2" />
                    <LineBorder color="170,170,170" />
                    <GradientBackground>
                        <color>white</color>
                        <color>223,223,223</color>
                    </GradientBackground>
                </decoration>
                <decoration states="focused">
                    <LineBorder color="85,130,190" />
                </decoration>
                <decoration states="expanded">
                    <WebShadow type="outer" opacity="0" />
                    <WebShadow type="inner" width="6" />
                    <ColorBackground color="210,210,210" />
                </decoration>
                <decoration states="disabled">
                    <WebShadow type="outer" opacity="0" />
                    <LineBorder color="lightGray" />
                </decoration>
            </decorations>
        </painter>
        
        ...
        
    </style>
```
You can see that there are two different backgrounds used for default and `expanded` states. You can adjust those or simply override the whole style if you need. Here are two examples of how you can make combobox background to be plain in normal state:

- For all existing comboboxes (overriding default combobox style within new skin):
```xml
<skin>

    <!-- Skin settings -->
    <id>example.skin</id>
    <class>example.ExampleSkin</class>
    <supportedSystems>all</supportedSystems>

    <!-- Skin information -->
    <title>Example skin</title>
    <description>Some example skin</description>
    <author>Mikle Garin</author>

    <!-- Including WebLaF default skin, will use its style as a base -->
    <include nearClass="com.alee.skin.web.WebSkin">resources/skin.xml</include>

    <!-- Combobox -->
    <style type="combobox">
        <painter>
            <decorations>
                <decoration>
                    <ColorBackground color="223,223,223" />
                </decoration>
            </decorations>
        </painter>
    </style>

</skin>
```
- For specific comboboxes (creating custom style within a skin extension):
```xml
<skin>

    <!-- Extension settings -->
    <id>example.extension</id>
    <class>example.ExampleSkinExtension</class>
    <extends>weblaf.web.skin</extends>

    <!-- Combobox -->
    <style type="combobox" id="mycombo">
        <painter>
            <decorations>
                <decoration>
                    <ColorBackground color="223,223,223" />
                </decoration>
            </decorations>
        </painter>
    </style>

</skin>
```
Which way of the two to choose depends on the usage case. Whenever you need to change default style for any of existing components - you will have to create a separate skin. But if you only need to customize style for some specific use cases - skin extensions are more than enough. You can also use both approaches together - redefine default styles in a custom skin and provide all additional styles within extensions. All that is up to you to decide.

#### Using v1.29 pre-release build or older

Older versions offered a lot less options so you might find a lot of things simply being unconfigurable. In case with the old `JComboBox` styling - you are able to switch between gradient background and simple single-color background there by changing this static field value to `false`:
```java
WebComboBoxStyle.webColoredBackground = false;
```
In that case combobox background color and `WebComboBoxStyle.expandedBgColor` colors are used for combobox background.

It might seem that older way of styling things was easier, but it had a lot of critical flaws. That is why style settings were completely separated and even moved into XML instead of code. There will be a way to configure styles using code with newer versions, but it will come simply as an enhancement for current way of styling.

**Comment by mgarin** [comment]
Did my answer help you or you still have some questions?

**Comment by EricCong2016** [comment]
Thanks for the explanation:+1:

**Comment by mgarin** [comment]
:)
I'll be closing this question then.

**Comment by wyj3531** [comment]
textfield background can do,but how to set it LineBorder color

**Comment by wyj3531** [comment]
`    <style type="textfield" id="mycustom">
        <painter>
            <decorations>
                <decoration>
                    <ColorBackground color="237,238,255"/>
                    <LineBorder color="237,238,255"/>
                </decoration>
           
            </decorations>
        </painter>
    </style>`

**Comment by wyj3531** [comment]
<style type="textfield" id="mycustom">
        <painter>
            <decorations>
                <decoration>
                    <ColorBackground color="237,238,255"/>
                    <LineBorder color="237,238,255"/>
                </decoration>
            </decorations>
        </painter>
    </style>

**Comment by wyj3531** [comment]
<style type="textfield" id="mycustom">
        <painter>
            <decorations>
                <decoration>
                    <ColorBackground color="237,238,255"/>
                    <LineBorder color="237,238,255"/>
                </decoration>
            </decorations>
        </painter>
    </style>

**Comment by mgarin** [comment]
@wyj3531 
Style you've posted should work for modifying the `textfield` border color, or it doesn't for you?

Also in general - I recommend looking into default styles, you can often find things you might want to change specified in them. For instance for `textfield` component it's `textfield.xml` (light and dark variations):
- light: https://github.com/mgarin/weblaf/blob/master/modules/ui/src/com/alee/skin/light/resources/textfield.xml#L24
- dark: https://github.com/mgarin/weblaf/blob/master/modules/ui/src/com/alee/skin/dark/resources/textfield.xml#L24

**Comment by wyj3531** [comment]
the line color can work,but when i edit textfield ,the line color change. i just want to all state the background and line color in same color. use the code i can not work. why?

**Comment by mgarin** [comment]
There are three different states described in the default style:
```xml
<decorations>
    <decoration>
        <WebShape round="2" />
        <WebShadow type="outer" width="2" />
        <LineBorder color="170,170,170" />
        <ColorBackground color="white" />
    </decoration>
    <decoration states="focused">
        <LineBorder color="85,130,190" />
    </decoration>
    <decoration states="disabled">
        <WebShadow type="outer" opacity="0" />
        <LineBorder color="lightGray" />
    </decoration>
</decorations>
```
Each of them defines a different color. In the custom style you've posted you're only overriding the basic color, but not the focused/disabled ones. If you want the field to have the same border color in all of those states there are two options:

1. Override all states:
```xml
<style type="textfield" id="mycustom">
    <painter>
        <decorations>
            <decoration>
                <ColorBackground color="237,238,255"/>
                <LineBorder color="237,238,255"/>
            </decoration>
            <decoration states="focused">
                <LineBorder color="237,238,255"/>
            </decoration>
            <decoration states="disabled">
                <LineBorder color="237,238,255"/>
            </decoration>
        </decorations>
    </painter>
</style>
```

2. Overwrite all decoration states of the default style:
```xml
<style type="textfield" id="mycustom">
    <painter>
        <decorations overwrite="true">
            <decoration>
                <WebShape round="2" />
                <WebShadow type="outer" width="2" />
                <ColorBackground color="237,238,255"/>
                <LineBorder color="237,238,255"/>
            </decoration>
        </decorations>
    </painter>
</style>
```

In the 2nd case you'll have to specify all settings of your decorations though because they will not be inherited from the decorations - instead your settings in `<decorations>` block will completely overwrite ones from default style.
