### ISSUE TITLE
Chinese will be garbled

### ISSUE THREAD

**Issue by sbfkcel** [mgarin/weblaf#429]
Chinese will be garbled
![snipaste20161223_110647](https://cloud.githubusercontent.com/assets/5469785/21446350/fd415b5a-c8ff-11e6-9e06-81f8df81fddd.png)

**Comment by mgarin** [comment]
This is a known problem. Unfortunately right now WebLaF is using hardcoded fonts which do not work with some languages too well. This problem will be solved upon introduction of font management improvements described here: #331 

Since this is a general problem I will be closing this issue pointing at the specific place where it appears. If you want to get notified as soon as fix appears you can subscribe to receive notifications from #331

**Comment by sbfkcel** [comment]
Think you~~
look forward to

**Comment by mgarin** [comment]
Just a small note on this one - even though ticket #331 haven't been completed yet - there have been some major improvements in the way how WebLaF handles fonts. Even if the hardcoded or system-provided fonts do not support some symbols - used fonts now have a fallback font that in most cases should be able to handle those symbols. It might lead to some minor visual degradation of the font rendering (in cases when text cannot be rendered with default font), but it is certainly better than not seeing the text at all in the first place.
