### ISSUE TITLE
JTextField background color changing not working in WebLAF

### ISSUE THREAD

**Issue by MalindaWMD** [mgarin/weblaf#430]
Hi,
I change JtextField color in my JFrame and i installed WebLookAndFeel, but Textfield color didn't change. Hoe can i change background color of a JtextFiled with WebLAF ?
Thank you

**Comment by mgarin** [comment]
WebLaF handles components styling quite differently from other L&Fs and doesn't use some of the default settings due to their limitations. For example default WebLaF button uses two colors for its background so there is no good way to use single background color of the component. 

Also purpose of of the component background color is to fill-in the whole component area (bounds) with that color while WebLaF components don't use the whole area to paint themself (shadow and rounded corners leave out some space), so it isn't really applicable. In WebLaF background color is only used to fill-in the actual background behind the components when specific component is opaque, but they mostly aren't so it is simply not used.

If you want to re-style component using WebLaF you would need to change its style instead of changing the background color or any other settings on the component. I have given an expanded answer on how that could be done for combobox recently in this question - #425 - it is pretty much the same for the text field or any other component.

And as it was mentioned in the answer there - I would recommend reading this [styling introduction article on the wiki](https://github.com/mgarin/weblaf/wiki/Styling-introduction) first.

The whole styling system might feel as an overkill and overcomplicated at the start, but as soon as you start working with at least a bit larger application that requires different styles for specific UI elements it does the job. Basically you can re-style any component to your liking using the default provided tools in an instant or write your own extensions for border, shadow, background etc. to provide unique component look and feel.

**Comment by MalindaWMD** [comment]
Thank you Mikle
I saw tha issue #425 after posting my question. Yes that worked. I made a
simple class to color textfield, according to your answer.
Thank you again.
Good luck :-)

**Comment by mgarin** [comment]
Glad to hear that!
I will be closing this issue then.

Feel free to post any other questions here or ask them on [Gitter chat](gitter.im/mgarin/weblaf) - the latter might be more convenient for some cases :)
