### ISSUE TITLE
WebCollapsiblePane collapse problem

### ISSUE THREAD

**Issue by sailsoft** [mgarin/weblaf#454]
when use the **setPreferredSize()** method to resize WebCollapsiblePane,the **collapse()** invalidation.

**Comment by sailsoft** [comment]
final WebCollapsiblePane rightPane = new WebCollapsiblePane ( icon, "right pane", createCustomVerContent () );
        rightPane.setTitlePanePostion ( SwingConstants.LEFT );
     // Split
        WebSplitPane splitPane = new WebSplitPane ( javax.swing.JSplitPane.HORIZONTAL_SPLIT, leftPanel, rightPane );
        splitPane.setOneTouchExpandable ( true );
        splitPane.setPreferredSize ( new Dimension ( 250, 200 ) );
        splitPane.setDividerLocation ( 125 );
        splitPane.setContinuousLayout ( true );

**Comment by mgarin** [comment]
The thing with collapsible pane is that it fills-in the whole available in your example because container dictates it to do so. That would be the same if you place a `JButton` in one of the sides.

If you want collapsible pane to properly collapse itself - you need to allow it to take its preferred size in the collapse/expand directions. In your specific case it is left and right directions.

So here is what you can do:
```java
public class PreferredCollapsiblePane
{
    public static void main ( final String[] args )
    {
        WebLookAndFeel.install ();

        final WebLabel leftPane = new WebLabel ();

        final WebCollapsiblePane collapsiblePane = new WebCollapsiblePane ( "right pane", new WebLabel ( "content" ) );
        collapsiblePane.setTitlePanePosition ( SwingConstants.LEFT );

        final WebPanel rightPane = new WebPanel ( new BorderLayout () );
        rightPane.add ( collapsiblePane, BorderLayout.WEST );

        final WebSplitPane splitPane = new WebSplitPane ( JSplitPane.HORIZONTAL_SPLIT, leftPane, rightPane );
        splitPane.setOneTouchExpandable ( true );
        splitPane.setPreferredSize ( new Dimension ( 250, 200 ) );
        splitPane.setDividerLocation ( 125 );
        splitPane.setContinuousLayout ( true );

        TestFrame.show ( splitPane, 50 );
    }
}
```

Though it will be a bit harder if you need to stretch collapsible pane to the whole size of the right side, but it can still be achieved with a custom layout.

The thing is - I'm not sure why would you want to use collapsible pane in such a way that it leaves a lot of free space on the screen when collapsed - that is simply not user-friendly nor useful anyhow. Collapsible pane is designed to allow hiding chunks of UI to provide extra space for other UI elements.

Here is a small usage example:
```java
public class PreferredCollapsiblePane
{
    private static final String text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, " +
            "sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. " +
            "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris " +
            "nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in " +
            "reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla " +
            "pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa " +
            "qui officia deserunt mollit anim id est laborum.";

    public static void main ( final String[] args )
    {
        WebLookAndFeel.install ();

        final WebPanel container = new WebPanel ( new BorderLayout ( 10, 0 ) );

        final WebTextArea textArea = new WebTextArea ( text, 10, 25 );
        textArea.setLineWrap ( true );
        textArea.setWrapStyleWord ( true );
        container.add ( new WebScrollPane ( textArea ), BorderLayout.CENTER );

        final WebCollapsiblePane collapsiblePane = new WebCollapsiblePane ( "Title", new WebLabel ( "content" ) );
        collapsiblePane.setTitlePanePosition ( SwingConstants.LEFT );
        container.add ( collapsiblePane, BorderLayout.EAST );

        TestFrame.show ( container, 50 );
    }
}
```
It actually makes sense because collapsing the pane frees more space for the text area so the user can read it more easily and he can always expand the pane again if he needs to access its content.

**Comment by mgarin** [comment]
Generally speaking - I'm not sure if the current collapsible pane behavior will be changed in the future versions or not. I'll be reworking it to simplify and cleanup its code and fix some minor issues and I will think about it again then.
