### ISSUE TITLE
WebLaF messes up the Java Default Locale

### ISSUE THREAD

**Issue by manticore-projects** [mgarin/weblaf#457]
OS
```bash
are@localhost ~> locale
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=
```

JDK/Java:
```java
System.out.println(Locale.getDefault()); // returns en_US as expected


SwingUtilities.invokeLater(new Runnable() {
        @Override
        public void run() {
          WebLookAndFeel.initializeManagers();
          System.out.println(Locale.getDefault()); // returns en_GB which is incorrect
        }
      });

SwingUtilities.invokeLater(new Runnable() {
        @Override
        public void run() {
          WebLookAndFeel.initializeManagers();
          Locale.setDefault(Locale.US);
          System.out.println(Locale.getDefault()); // returns en_US as expected, 
                                                                         // but enforces a certain locale which is 
                                                                         // unacceptable of course
        }
      });

```

Now, the issue is: while the language English seems to be correct, Date and Number formats are messed up completely by that. Enforcing en_US is also not an option for an software, which supports various languages. Accepting en_GB does not work either, as any other component (Database, Reports, Spreadsheets) will correctly parse/format according to en_US.

We would like to suggest to not temper with the frameworks settings as it breaks things too easily and is difficult to trace.

**Comment by mgarin** [comment]
This is a small feature integrated into `LanguangeManager` and enabled by default. `Locale` is being automatically set according to the selected language - `en` by default which leads to `en_GB` locale. 

You can disable it like this:
```java
LanguageManager.setUpdateLocale ( false );
```
Note that you need to do that strictly before installing L&F or initializing L&F managers, otherwise locale will be updated according to the language set in the manager.

Though I do agree that `Locale` management is currently quite poor, so I'll mark this issue as an enhancement and will look into that in the future updates.

**Comment by manticore-projects** [comment]
Thank you a lot for prompt response, much appreciated.
On Fri, 2017-06-02 at 10:51 -0700, Mikle wrote:
> This is a small feature integrated into LanguangeManager and enabled by default. Locale is being automatically set
> according to the selected language - en by default which leads to en_GB locale.
You will have to manage quite a few locale/language pairs for English/French/German/Portuguese/Spanish that way, which
ends up mostly in identical translations. Why not honor the REGION/COUNTRY settings of the JDK?
> You can disable it like this:
> 
> LanguageManager.setUpdateLocale ( false );

Awesome, this was what I was looking for!Suggestion: mention it perhaps in the basic howtos/instructions. The default
behavior is unexpected and hard to trace.
> Though I do agree that Locale management is currently quite poor, so I'll mark this issue as an enhancement and will
> look into that in the future updates.
> 

Suggestion: set the language only, but do not alter the region/country and honor especially the JVM Options.
Thank you again for helping and best regardsAndreas

**Comment by manticore-projects** [comment]
On Fri, 2017-06-02 at 10:51 -0700, Mikle wrote:
> LanguageManager.setUpdateLocale ( false );

No wonder though that I did not find that: WebLAF 1.29 does not seem to have such a static public method in class
LanguageManager.
What version exactly is it referring to please?

Best regards
Andreas

**Comment by mgarin** [comment]
I'm generally referencing latest [styling](https://github.com/mgarin/weblaf/tree/styling) branch snapshot builds as all other artifacts are a least a year+ older and contain a lot of issues which have already been fixed, so I strongly recommend using newer ones.

You can find them on the snapshot maven repository:
https://oss.sonatype.org/content/repositories/snapshots/

Also newer versions contain a lot of API changes and appropriate styling system implementation for the UI, so it is much more useful for anyone who would like to customize things.

And yes, I know that versioning is in a mess right now (due to me trying to stick in too many things in one update), but I have to get through v1.2.9 release to manage all of the stuff properly in the future updates.

**Comment by mgarin** [comment]
> You will have to manage quite a few locale/language pairs for English/French/German/Portuguese/Spanish that way, which ends up mostly in identical translations. Why not honor the REGION/COUNTRY settings of the JDK?

There have been a similar question some time ago in #272 - I will certainly look into possible options when I will be working on `LanguageManager` enhancements, but I'm not sure yet how exactly it will function.

**Comment by mgarin** [comment]
> Suggestion: set the language only, but do not alter the region/country and honor especially the JVM Options.

This, unfortunately, won't always work as you would want to, so it's not a perfect solution either. But I will be looking into options when I will be working on the enhancements.

**Comment by mgarin** [comment]
> Suggestion: mention it perhaps in the basic howtos/instructions. The default behavior is unexpected and hard to trace.

I will make sure to add this this to wiki along with the other changes coming with this enhancements.

**Comment by mgarin** [comment]
Some major changes for `LanguageManager` are coming, those will address this issue and many others and will also bring a lot of overall improvements and a few new features.

You can read more about the upcoming changes here:
https://github.com/mgarin/weblaf/issues/272#issuecomment-340807841

**Comment by mgarin** [comment]
Changes are now available in `styling` branch.
`Locale` will never be adjusted by `LanguageManager` by default anymore.
To return previous behavior (`Locale` update to current language) you can add one extra line of code:
```java
LanguageManager.addLanguageListener ( new LanguageLocaleUpdater () );
```
