### ISSUE TITLE
Can'tshow unicode characters in file chooser

### ISSUE THREAD

**Issue by trigchen** [mgarin/weblaf#486]
In Chinese Windows, the file chooser can't show Chinese characters. 
Please see the issue in attachments.
![image1](https://user-images.githubusercontent.com/18128742/41154020-4a9ac5fa-6b4b-11e8-964f-2257d542e333.png)
![image2](https://user-images.githubusercontent.com/18128742/41154025-4e2316f0-6b4b-11e8-8f8d-8db61b20540b.png)

**Comment by mgarin** [comment]
Judging by the screenshot - you're running one of the earlier versions of WebLaF (either v1.28 or early v1.29 preview). This issue have been addressed since then, but only in [styling](https://github.com/mgarin/weblaf/tree/styling) branch code which is still being developed for the final huge release I'm working on. 

Code from `styling` branch is basically a major rework/revamp for multiple APIs, components and codebase. So, obviously, it contains a lot of API breaks and might be inconvenient to move to in case you were using any extended APIs of the older L&F versions. But if you were using WebLaF as L&F only - it should be a pretty simple transition.

At this point I can quite safely say that even though `styling` branch haven't been officially released yet it is much more stable than any previous versions of the library and contains quite a few new features on top of that, so I would certainly recommend switching to it if possible.

You can find latest snapshot builds from the `styling` branch here:
https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/

You can also specify it as a maven project dependency:
```xml
    <dependencies>
        <dependency>
            <groupId>com.weblookandfeel</groupId>
            <artifactId>weblaf-ui</artifactId>
            <version>1.2.9-SNAPSHOT</version>
        </dependency>
    </dependencies>
```
But you will also need to specify Sonatype snapshot repository:
```xml
    <repositories>
        <repository>
            <id>sonatype-snapshot-rep</id>
            <name>Sonatype snapshot repository</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <layout>default</layout>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>never</updatePolicy>
            </releases>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>never</updatePolicy>
            </snapshots>
        </repository>
    </repositories>
```

**Comment by mgarin** [comment]
Also, for reference - #331 is a general topic where I post updates regarding fonts management within WebLaF. There will surely be more improvements coming to fonts management in the future updates.

**Comment by mgarin** [comment]
I will be closing this issue as it shouldn't appear anymore in newer versions.

Also due to scale of the changes I cannot easily port this solution into the older version, so unfortunately the only way to avoid this problem is to port the code over to newer version.
