### ISSUE TITLE
Component layout in menu bar

### ISSUE THREAD

**Issue by stefan-reich** [mgarin/weblaf#491]
Hi, I put things like JTextFields in my menu bar. With WebLAF (latest snapshot), the layouting of these components is different than with other PLAFs.

[JTattoo](http://ai1.space/1004590/raw/1101339) (see input field on top of screen, correct)
[WebLAF](http://ai1.space/1004590/raw/1101338) (not correct)

Menu making code:
```
      [add normal menus, then:]

      menuBar.add(Box.createHorizontalStrut(20));
      menuBar.add(new JTextField(...));
      menuBar.add(Box.createHorizontalStrut(20));
      menuBar.add(new JLabel(...));
      menuBar.add(Box.createHorizontalStrut(6));
```

**Comment by mgarin** [comment]
That happens because WebLaF menu bar uses a custom layout - `com.alee.laf.menu.MenuBarLayout`, so any `BoxLayout` solution won't work with it.

Generally speaking - most Swing (maybe even all) components API does NOT guarantee that they will have any specific layout by default and are free to use different ones in different implementations. That is exactly the case with `JMenuBar` in WebLaF - custom layout is used to simplify components positioning within menu bar. As another example - `JPanel` uses `BorderLayout` by default when WebLaF is installed instead of `FlowLayout`.

So my general recommendation is to apply layout to menu bar to ensure it has one you are expecting to be there, so in your case it can be:
```java
new DefaultMenuLayout ( menuBar, BoxLayout.LINE_AXIS )
```
(taken from `BasicMenuBarUI` implementation, basically it is a normal `BoxLayout`)

That might be the best solution in case you are going to provide a choice of L&F for end-user which means different L&Fs might be used with the same code.

**Comment by stefan-reich** [comment]
[It works](http://ai1.space/1004590/raw/1101345), thanks a lot!

**Comment by mgarin** [comment]
Glad that helped!

Generally speaking - I try to keep WebLaF's component implementation's behavior close to original implementation's behavior (view, layout, settings, etc), but sometimes it is just so lacking or plain bad that I'm forced to change things to avoid using workarounds. 

In this particular case - default menu bar layout is really lacking and things like the `Box` class from your example are used to workaround bad default layout choice. `BoxLayout` is not in fault here is it is a completely legit layout, but it just shouldn't be used for menu bar as it doesn't allow you to directly position elements the way you normally want to.

**Comment by stefan-reich** [comment]
Well, I want the menu bar to look like this... if there is a "cleaner" way to do it, I'll gladly switch...

**Comment by mgarin** [comment]
Here is an example using the default menu bar layout (`MenuBarLayout`) that is set by WebLaF:
```java
        final JMenuBar menuBar = new JMenuBar ();

        final JLabel version = new JLabel ( "Stefan's OS v6" );
        version.setBorder ( BorderFactory.createEmptyBorder ( 0,8,0,8 ) );
        menuBar.add ( version );

        menuBar.add ( new JMenu ( "Modules" ) );
        menuBar.add ( new JMenu ( "More" ) );

        final JTextField textField = new JTextField ( "I like your paperback", 1 );
        textField.setHorizontalAlignment ( SwingConstants.CENTER );
        menuBar.add ( textField, MenuBarLayout.FILL );

        final JLabel time = new JLabel ( "13:54" );
        time.setBorder ( BorderFactory.createEmptyBorder ( 0,8,0,8 ) );
        menuBar.add ( time, MenuBarLayout.END );
```
The main thing with this approach is that you don't need any custom components to fill-in or create gaps unlike the `BoxLayout` case.

And here is the result:
![image](https://user-images.githubusercontent.com/2361389/42136169-3ed9ceca-7d5f-11e8-9c0b-d15b92ae48a7.png)

Obviously I'm not saying you should use that approach, especially if you are going with multiple L&Fs, but just showcasing that it can be done differently :)
