### ISSUE TITLE
com.alee.extended.button.WebSplitButton Usage

### ISSUE THREAD

**Issue by mvrozanti** [mgarin/weblaf#508]
Hi there
I've been using this great library for a few days now and I've encountered some weird behaviour with WebSplitButtons. 

I thought the default behaviour when clicking the "main" button were to use some default `Action`

And if I clicked on the tiny arrow at the right this default `Action` would *not* be triggered, and the popup menu would be opened without side-effects. But apparently it doesn't. Is this the expected in production-grade software? Just asking, really.

Thanks!

**Comment by mgarin** [comment]
That is an expected behavior because `WebSplitButton` is in fact just a small upgrade added on top of simple `JButton`. It is not a component built from zero like some other components in WebLaF library. That is why all default `JButton` behaviors are preserved, including `ActionListener` firing upon pressing anywhere on the button, even on the split menu icon.

That being said, `WebSplitButton` has it's own `SplitButtonListener` that can be used instead of `ActionListener` to distinct two main events that occur on it, here is a small example:
```java
public class SplitButtonExample
{
    public static void main ( final String[] args )
    {
        SwingUtilities.invokeLater ( new Runnable ()
        {
            @Override
            public void run ()
            {
                WebLookAndFeel.install ();

                final WebSplitButton button = new WebSplitButton ( "Test" );

                final JPopupMenu menu = new JPopupMenu ();
                menu.add ( new JMenuItem ( "Item 1" ) );
                menu.add ( new JMenuItem ( "Item 2" ) );
                menu.add ( new JMenuItem ( "Item 3" ) );
                button.setPopupMenu ( menu );

                /**
                 * Common {@link ActionListener} usage.
                 * It will be fired whenever you click anywhere on the button.
                 */
                button.addActionListener ( new ActionListener ()
                {
                    @Override
                    public void actionPerformed ( final ActionEvent e )
                    {
                        System.out.println ( "Action performed" );
                    }
                } );

                /**
                 * Custom {@link SplitButtonListener} usage.
                 * It has separate events for button and split button clicks.
                 */
                button.addSplitButtonListener ( new SplitButtonListener ()
                {
                    @Override
                    public void buttonClicked ( final ActionEvent e )
                    {
                        System.out.println ( "Button clicked" );
                    }

                    @Override
                    public void splitButtonClicked ( final ActionEvent e )
                    {
                        System.out.println ( "Split button clicked" );
                    }
                } );

                TestFrame.show ( button );
            }
        } );
    }
}
```

I wouldn't deny that most library users would probably expect `ActionListener` to react only to non-menu area clicks - that is exactly why I would prefer keeping this issue open for the future updates coming for `WebSplitButton` component to make sure this is included as one of enhancements.

**Comment by mgarin** [comment]
I've added a separate issue for future improvements: #569
I'll update it once I have specific improvements plan in mind
