### ISSUE TITLE
JCheckBox as TableCellRenderer is inconsistent with model

### ISSUE THREAD

**Issue by mvrozanti** [mgarin/weblaf#509]
Hi there! I come again with a question with the following SSCCE:

```
public class BooleanCellRenderer extends JCheckBox implements TableCellRenderer {

	@Override
	public Component getTableCellRendererComponent(JTable jtable, Object o, boolean isSelected, boolean hasFocus, int row, int column) {
		setSelected(o != null && ((Boolean) o));
		return this;
	}

	public static void main(String[] args) {
//		WebLookAndFeel.install(); // <--- including this makes the the JCheckBoxes inconsistent with model below
		JFrame f = new JFrame();
		JTable jtable = new JTable(
				new Object[][]{
					new Object[]{1,true},
					new Object[]{2,false},
					new Object[]{3,null}
				}, 
				new Object[]{"column0","column1"});
		jtable.getColumnModel().getColumn(1).setCellRenderer(new BooleanCellRenderer());
		JScrollPane jsp = new JScrollPane(jtable);
		f.add(jsp);
		f.setLocationRelativeTo(null);
		f.setVisible(true);
	}

}
```

Installing WebLAF produces different behavior when rendering the `JComboBox`es:

![image](https://user-images.githubusercontent.com/11381662/56997102-00cc8c00-6b7d-11e9-9a7f-8c3ae21d909d.png)

Correct me if I'm wrong but this may be related to JCheckBox animation added in WebLAF
Is this expected behavior? Is there an easy workaround?

**Comment by mvrozanti** [comment]
Fixed with:
`CoreManagers.initialize();`
Before LAF installation

**Comment by mvrozanti** [comment]
Making `BooleanCellRenderer` extend `WebCheckBox` fixes the problem!

**Comment by mgarin** [comment]
Sorry for the delay, been away for one week. Even though you did find a solution - I would still like to clarify why renderer had the issue you observed.

In older library versions - default check box style had animation "baked" into it, but unfortunately due to specifics of how cell renderers are being rendered (whether it is a list, table or tree - doesn't really matter in most cases) - it got stuck on first component state as the animation kicks-in only when component becomes visible. If it doesn't, which is the case with renderer, animation stays at "zero" which is visually an unchecked state for the checkbox.

The code you have provided in the first post works properly for me on latest WebLaF version due to removal of the animation in default checkbox style:

![image](https://user-images.githubusercontent.com/2361389/57230350-d9fcd280-7020-11e9-955e-699ce71c3183.png)

![image](https://user-images.githubusercontent.com/2361389/57230380-e5e89480-7020-11e9-9647-2e3c8a4e8a9c.png)

Also, most recent versions of WebLaF have multiple predefined renderers - for instance `WebTableBooleanCellRenderer` for the table - that can be used to avoid any issues and preserve all visual styles applied by custom skins.

Here is an example that should never have issues rendering checkbox in a table:

```java
public class BooleanCellRenderer
{
    public static void main ( final String[] args )
    {
        SwingUtilities.invokeLater ( new Runnable ()
        {
            @Override
            public void run ()
            {
                WebLookAndFeel.install ();

                final JTable jtable = new JTable (
                    new Object[][]{
                        new Object[]{ 1, true },
                        new Object[]{ 2, false },
                        new Object[]{ 3, null }
                    },
                    new Object[]{ "column0", "column1" }
                );
                jtable.getColumnModel ().getColumn ( 1 ).setCellRenderer ( new WebTableBooleanCellRenderer () );
                jtable.getColumnModel ().getColumn ( 1 ).setCellEditor ( new WebBooleanEditor () );

                TestFrame.show ( new JScrollPane ( jtable ) );
            }
        } );
    }
}
```

That being said, usage of existing renderers like `WebTableBooleanCellRenderer` is recommended but certainly not required. In newer library versions your boolean renderer and any other custom ones should work just fine.

**Comment by mvrozanti** [comment]
Thanks for the clarification
