### ISSUE TITLE
WebButton 1.2.9 - rolloverDecoratedOnly not available

### ISSUE THREAD

**Issue by mvanassche** [mgarin/weblaf#514]
I am testing 1.2.8 and testing a switch to 1.2.9.
For some buttons, I wanted to make them look flat, so I used rolloverDecoratedOnly,
but in 1.2.9, that property is no longer available.

What would be the proper way to do the equivalent in 1.2.9?

**Comment by mgarin** [comment]
In v1.2.9 all styling options were moved to the dedicated XML style files which dictate how all components are visually composed. It is certainly a more obscure way and it is harder to grasp than just setting a few options directly in the component, but it removes styling from the code completely to avoid cluttering it. It is somewhat similar to HTML & CSS approach where you want to keep your styles separate from the markup.

### Skin vs Extension

To configure any component in v1.2.9 and all future versions you will need to first decide whether you want to create a fully custom **skin** or a **skin extension**.

**Skin** is a standalone group of styles - either packed in a single or multiple XML files - that can be used in WebLaF as a main theme. Skins can be easily switched in runtime and will not have most of the downsides of switching between different L&Fs in runtime. Each skin should contain styles for all existing components because those styles will be used as default for all those components. The downside of making a custom skin is the increased  That being said - you can extend existing skins and override only the styles you want to modify while leaving everything else intact.

Here is an example of default light skin in v1.2.9: [skin.xml](https://github.com/mgarin/weblaf/blob/styling/modules/ui/src/com/alee/skin/web/resources/skin.xml)
And a button style from it (one of includes in skin.xml): [button.xml](https://github.com/mgarin/weblaf/blob/styling/modules/ui/src/com/alee/skin/web/resources/button.xml)

**Extension** is a group of styles - either packed in a sinle or multiple XML files - that can be applied to any/multiple existing skins at once but always depends on those skins and cannot function without them. Extension allows you to make a single style that will apply to multiple specified skins - whichever is active at the time, so for instance you can make a flat button style that will inherit colors from light & dark skins so you don't need to worry about them. The downside of extension - it cannot modify base styles - so you can't for instance change default button style, you can only make a new custom button style in your extension that you can later on apply to any existing button component instance (but you will have to apply it manually or create a button extension class that uses it by default). Also extension might not always be applicable to multiple existing skins if you want to use some custom colors and whatnot as it will simply look bad on either light or dark skin, meaning you will still sometimes need to make separate extension for separate skins.

Here is an example of multi-skin applicable extension from demo app: [extension.xml](https://github.com/mgarin/weblaf/blob/styling/modules/demo/src/com/alee/demo/skin/resources/adaptive/extension.xml)
And light/dark skin extensions from the same demo: [extension.xml](https://github.com/mgarin/weblaf/blob/styling/modules/demo/src/com/alee/demo/skin/resources/light/extension.xml) [extension.xml](https://github.com/mgarin/weblaf/blob/styling/modules/demo/src/com/alee/demo/skin/resources/dark/extension.xml)

If you are aiming at modifying base styles - for instance you want to change how all buttons look like in your application - I recommend going with a custom skin based on some existing default skin. So for the next example I will go along with that suggestion and show a short example of how custom skin can be created and applied to your app.

### Example

First you will need to make a custom skin class [MyFlatSkin.java]: 
```java
package com.weblaf.test.skin;

import com.alee.managers.style.XmlSkin;

/**
 * @author Mikle Garin
 */
public class MyFlatSkin extends XmlSkin
{
    public MyFlatSkin ()
    {
        super ( MyFlatSkin.class, "resources/skin.xml" );
    }
}
```
You will need it later, to apply your custom skin as application skin.

Next you need the most important part - skin itself [skin.xml]:
```xml
<skin xmlns="http://weblookandfeel.com/XmlSkin">

    <!-- Skin settings (required) -->
    <id>my.flat.skin</id>
    <class>com.weblaf.test.skin.MyFlatSkin</class>
    <supportedSystems>all</supportedSystems>

    <!-- Skin information (optional) -->
    <icon>icons/icon.png</icon>
    <title>My Flat Skin</title>
    <description>My Custom Flat Skin Example</description>
    <author>Mikle Garin</author>

    <!-- Including WebLaF default light skin, will use its style as a base -->
    <include nearClass="com.alee.skin.web.WebSkin">resources/skin.xml</include>

    <!-- Customizing base button style -->
    <style type="button">
        <painter>
            <decorations>
                <decoration>
                    <WebShape round="1" />
                    <WebShadow type="outer" width="1" />
                </decoration>
            </decorations>
        </painter>
    </style>

</skin>
```
This is a rather simple adjustment to the button style - only round & shadow are modified to make button look different. We don't need to copy-paste all default button styles - they will be taken from the skin we're including at the top - `WebSkin` - which is a default light skin. You can add more settings to that style whenever you want and you can modify other styles as well. To see how exactly settings are specified you can check XSDs available for the styles or simply look into the existing component style. Here is the button one for reference: [button.xml](https://github.com/mgarin/weblaf/blob/styling/modules/ui/src/com/alee/skin/web/resources/button.xml) (yes, I already linked it as an example above)

Also we specified in `MyFlatSkin` class that skin should be located nearby in a `resources` folder, it will have to be there, otherwise skin class won't be able to find the XML file.

Now we're almost done, we just need a sample application:
```java
package com.weblaf.test.skin;

import com.alee.extended.window.TestFrame;
import com.alee.laf.WebLookAndFeel;

import javax.swing.*;

/**
 * @author Mikle Garin
 */
public class SampleApp
{
    public static void main ( final String[] args )
    {
        SwingUtilities.invokeLater ( new Runnable ()
        {
            public void run ()
            {
                WebLookAndFeel.install ();

                final JPanel panel = new JPanel ();
                panel.add ( new JButton ( "Simple button" ) );
                panel.add ( new JButton ( "Icon button", WebLookAndFeel.getIcon ( 16 ) ) );
                panel.add ( new JButton ( WebLookAndFeel.getIcon ( 16 ) ) );

                TestFrame.show ( panel );
            }
        } );
    }
}
```
And yes, you can use simple Swing components because once again - we will be changing base component styles, meaning those will apply by default to all components of the specific type - in this case to all buttons.

This is how it looks like:
![image](https://user-images.githubusercontent.com/2361389/62203357-ac12fa00-b393-11e9-817b-8efb62551b90.png)
We didn't apply our custom skin anywhere yet, so obviously this is the default style.

Now we simply need to apply our custom skin using one of the options.
First is the best one if you are simply using one skin:
```java
WebLookAndFeel.install ( MyFlatSkin.class );
```
Next if you want to apply/change skin at some later point or simply provide it separately:
```java
StyleManager.setSkin ( MyFlatSkin.class );
```
Note that this must be used after installing WebLaF and it will take double time as the default skin will always be loaded on WebLaF install unless a custom one is provided in `install()` method call like in the first example.

Now here is what we get in either case:
![image](https://user-images.githubusercontent.com/2361389/62203707-59860d80-b394-11e9-8ecf-3552af255b5c.png)

### Custom styles

You might not always want to create a style that will be applied to all existing components of a type, that is when you want to make a custom style.

Here is a small example style that can be added to `skin.xml` above:
```xml
    <!-- My custom icon button -->
    <style type="button" id="my-custom-icon" padding="10,10,10,10">
        <painter>
            <decorations>
                <decoration>
                    <WebShadow type="outer" width="5" />
                    <LineBorder color="140,140,140" />
                </decoration>
            </decorations>
        </painter>
    </style>
```
This is just a sample style for button with a larger shadow and padding.

Now, it won't really be used anywhere unless you apply it directly. So that is what I am going to do with the button from example above:
```java
panel.add ( new WebButton ( StyleId.of ( "my-custom-icon" ), WebLookAndFeel.getIcon ( 16 ) ) );
```
I am using `WebButton` instead of `JButton` now as it allows for convenience use of `StyleId` in it's constructor. But you can always use `StyleId.set ( component )` method to setup a specific `StyleId` into any basic Swing component like `JButton`. It is just less convenient, nothing else.

Here is how our example will look like now:
![image](https://user-images.githubusercontent.com/2361389/62205049-34df6500-b397-11e9-8659-222ed1ff0d0c.png)

Once again, this approach is only useful when you want to customize some specific UI elements while leaving the rest of the UI intact.

### Summary

Now while this have been a pretty long way to simply change a few properties on the button - there are a lot of upsides once you got here:

- Making any new style adjustments or new styles is a matter of seconds - just add them into the `skin.xml` and restart the app to see results or simply reload the skin in runtime.

- You can organize your component styles now, make custom ones and manage/apply them as you like. Applying default or custom style to any particular component is just one extra call or a constructor variable.

- Your code is now free from the styling clutter that in most cases has no meaningful impact on how your application logic works, but certainly makes it harder to read and understand the code.

- You can now switch between different skins with a single method call if you want to and unlike switching between L&Fs it has no downsides to it. Switching between L&Fs can sometimes lead to random UI clutter (elements/settings) being left behind  from the previous L&F which can hurt aestetics and cause random issues.

And there are a lot of other improvements I am planning to release in future updates that will further simplify styles creation and usage.

**Comment by mgarin** [comment]
I'll close this question now, but feel free to reopen it if you need further help with this question or open a new one about a different matter.
