### ISSUE TITLE
StyleId.buttonHover smooth animation

### ISSUE THREAD

**Issue by Husker-hub** [mgarin/weblaf#530]
How can I set ***smooth*** animation of ```StyleId.buttonHover``` like it was in WebLaF v1.28, using ```rolloverDecoratedOnly(true)```?

**Comment by mgarin** [comment]
If under "smooth" you mean the fade-in/fade-out animation - it is not supported in v1.2.9 (yet). This is one of the things I had to temporary cut from the library until better and more agile animation support is added to the new styling system. There are still some things that are animated, but transitions between component states have been left out because it is something that is controlled by the styling system now.

Animated transitions between states (with a lot more options to be used) will be added in v1.3.0 update, you can track #355 if you want to receive an update when it will be supported.

**Comment by Husker-hub** [comment]
Thanks
