### ISSUE TITLE
Trail in hovering WebScrollPane

### ISSUE THREAD

**Issue by Husker-hub** [mgarin/weblaf#551]
When I'm using ```hovering``` or ```transparent-hovering``` style, ```ScrollBar``` makes this trail that disappears after second. I have tried this style a month ago on WebLaF 1.28 and there were the same.

![image](https://user-images.githubusercontent.com/31825139/65908618-78724180-e3cf-11e9-8eac-5a964b9f4a39.png)

**Comment by Husker-hub** [comment]
Sometimes this bug disappears itself.

**Comment by mgarin** [comment]
To use any of the `hovering` styles you need to make sure that content that is in the scroll pane is non-opaque, it is a Swing limitation I can't really do much about.

**Comment by mgarin** [comment]
Just a note - this bug will disappear if the `Window` that scroll pane is positioned on acquires a glass pane, for instance due to displaying custom WebLaF tooltip somewhere. That happens because Swing has a workaround for repainting heavyweight components, but it is generally not a good idea to use it as it affects UI performance by basically making all opaque components appear as non-opaque for the `RepaintManager` and causing a lot of extra unnecessary repaint operations being made.

**Comment by mgarin** [comment]
Another note - there are various styles available for most components that make them non-opaque - for example `StyleId.panelNonOpaque` or `StyleId.panelTransparent`. Some other styles might also be using non-opaque as a base which effectively make them non-opaque as well, for instance `StyleId.panelDecorated` or `StyleId.panelFocusable`.

Not every component has those styles, but I've added them to those that are most often used within scroll panes - lists, trees, tables, panels etc.

**Comment by Husker-hub** [comment]
Why not disable ```opaque``` only when the background color doesn't have alpha channel and rounded borders?

**Comment by mgarin** [comment]
It works fine within one component and is already implemented actually in `AbstractDecorationPainter` used by almost all components, unless you explicitly make component opaque in the style. Some components are made opaque in the default style in WebLaF - like `panel` or `tree` for example - to preserve default behavior, not everyone need rounding as performance is often a more important concern, especially if end-users run the application on slower machines. Other components - like `label` or `button` - do not explicitly specify `opaque` parameter which effectively makes them non-opaque whenever decorations are present, that is okay because those components are usually not containers.

Now, all that I said above only applies to "within one component" condition, but in your original question here - about issues with using `hovering` scroll bar styles - we're talking about multiple components. Scroll bar that uses `hovering` style is actually hovering on top of the viewport, component that lies within it and anything that can be added on top of that component. This already involves at least 4 components - `JScrollPane` itself, `JScrollBar` hovering over the view, `JViewport` used by scroll pane and your component displayed within the viewport. And the issue appears when your `JScrollPane` is set to `hovering` style and your view component (or any other component placed on it) is opaque. Your opaque component might not be using any decorations, in fact - it might be a simple opaque panel, so the rule from above (make it non-opaque when it has decoration/semi-transparent background) doesn't apply to it and it is a correct behavior. So this approach doesn't really work for `hovering` scroll panes.

The only way to handle it is to actively make anything added within a `hovering` scroll pane non-opaque, but that will not work correctly with all different styles as those will dictate their own opaque value. On top of that it will require some extensive use of `HierarchyListener` which is never really a good idea due to how it impacts application performance. So the best solution is to either not use `hovering` style for complex cases (containers with multiple components in them being scrollable) or simply style things correctly on your own (which is quite easy with various `non-opaque` styles available for multiple components).

Hopefully that explains why I haven't done anything about it :)

**Comment by mgarin** [comment]
And just a separate note about component's opacity -

`JComponent`'s `opaque` flag exists to improve UI performance and nothing else. Obviously it might cause issues whenever two opaque components are intersecting within one `Container` (when their bounds within that `Container` intersect) - that causes exactly the visual "glitches" you are experiencing. Those are simply repaint artifacts, `RepaintManager` decides that it's "not worth" repainting some areas because according to the layout there is an opaque component displayed there and it has not yet changed. That optimization has its pros and cons. On of the major pros obviously being performance - Swing UI doesn't ever update when it's not needed effectively making it one of the most responsive UI libraries out there when used correctly. And one of the major cons is the necessity of managing opacity across your UI if it gets complex or uses any kinds of non-rectangular shapes for elements.
