### ISSUE TITLE
WebComboBox minimum width

### ISSUE THREAD

**Issue by Husker-hub** [mgarin/weblaf#585]
Minimum width of ```WebComboBox``` based on selected text of item. This breaks my ```GridLayout```. I tried to use ```setMinimumWidth``` to change width but it didn't work for me.

![image](https://user-images.githubusercontent.com/31825139/69453219-8069b480-0d74-11ea-8621-dfc482135cb4.png)
![image](https://user-images.githubusercontent.com/31825139/69453575-41882e80-0d75-11ea-862b-e6fb829798ec.png)

I want to cut the text like this:

![image](https://user-images.githubusercontent.com/31825139/69453440-f5d58500-0d74-11ea-9b8f-e393dfcb4502.png)

**Comment by Husker-hub** [comment]
I haven't read about JComboBox width. Here is solution:
setPreferredWidth(20);

**Comment by mgarin** [comment]
Just wanted to comment a bit on the original question -

Looking at your particular example - dockable frame size is hard set, so it simply gives free space it has to whatevr is placed inside of it. 

You're using a container with `GridLayout` that has the task of laying out your components which happen in `GridLayout.layoutContainer` method. It is fairly simple and straightforward, but it doesn't use minimum size of the components you place on it at all. In fact - it doesn't even use preferred size.

And the reason why your container gets outside of the visible bounds - you probably have a scroll pane on top of it. And scroll pane has a "bad habit" of respecting only preferred size of whatever is within the viewport. I mean, it can take any space it wants, so why respect minimum size in the first place?

So minimum size will not really affect anything in this particular case because it's simply not even used.

Preferred size will though, because it affects the `GridLayout` preferred size, which in turn affects the scroll pane viewport size.

---

And a few notes about minimum size overall -

Method `setMinimumWidth` might not work the way you are expecting it to, same goes for `setMinimumSize` available on any basic Swing component.

A lot of layouts often ignore minimum size and generally use preferred size instead. Some only use it in their own minimum size calculations (including `GridLayout`) which may make it seem like they ignore it as well, especially when the layout their container is placed into ignores the minimum size, or the container above it etc. 

Often to make minimum size do anything at all - you would need the whole hierarchy to respect the minimum size value which is quite hard. And in the end it might only affect the minimum size of the `Window` your UI is placed on, but that depends on many things.

So regarding the minimum size - I do not generally recommend using it. As well as maximum size actually which has it's own problems.

But if you do and you find that it doesn't work the way you'd expect it to - I generally recommend testing the same UI layout under pure Swing conditions to see if the problem persists. If it does this is most probably not an issue particularly with WebLaF, but a nuance of how layouting works with minimum sizes of components in Swing.

Just in case - I'm certainly not trying to shift the blame here, WebLaF had it's own share of bugs and weirdness with layout sizes over the years (which I hopefully fixed), but minimum and maximum sizes in Swing are known to confuse a lot of people about what they actually do and in many cases they won't do what you'd expect them to.
