### ISSUE TITLE
Red border in minimized WebDockableFrame 

### ISSUE THREAD

**Issue by Husker-hub** [mgarin/weblaf#596]
Why do I have red border in a minimized ```WebDockableFrame```? It became with ```WebLaF 1.2.11```.

### WebLaF 1.2.10
![image](https://user-images.githubusercontent.com/31825139/70344665-4071f980-186b-11ea-937d-62a5636e3ae3.png)
### WebLaF 1.2.11
![image](https://user-images.githubusercontent.com/31825139/70344703-64cdd600-186b-11ea-982d-a4b20cc30646.png)

**Comment by mgarin** [comment]
That is a bug, seems that I've accidentally replaced the border color in the base skin.
I've pushed a fix for it, it will be available in the v1.2.12 snapshot version shortly.

I'll also add a few dockable examples into demo later on to make sure I won't miss out on the visual issues in future updates. I've missed it because at this point I'm using `StyleId.dockablepaneCompact` and `StyleId.dockableframeCompact` styles for all dockable elements and those didn't have the same problem.

So there are a few options to solve this problem for now:
- Use custom skin with the border replaced in default style
- Use custom style for `WebDockableFrame` with the border replaced
- Use v1.2.12 snapshot version with the fix
- Use `StyleId.dockableframeCompact` (you might also like this one more)

I'm planning to switch to different versioning approach to easily release hotfixes like this one fast, but for now, unfortunately, next update will take some time.
