### ISSUE TITLE
Visual issue in round shape

### ISSUE THREAD

**Issue by Husker-hub** [mgarin/weblaf#598]
When I tested rounding I found this issue. It seems like shadow can't be rounded more than 10 (pixels probably). I also tried to set shadow's rounding value manually, but it didn't change

### With shadow
![image](https://user-images.githubusercontent.com/31825139/70565493-505b4780-1ba3-11ea-904e-3af370196cd7.png)
```xml
<style type="button">
    <painter>
        <decorations>
            <decoration>
                <WebShape round="22,0,0,0" />
                <WebShadow type="outer" width="9" />
            </decoration>
        </decorations>
    </painter>
</style>

```
### Without shadow
![image](https://user-images.githubusercontent.com/31825139/70565527-6406ae00-1ba3-11ea-98cb-16f293ff081a.png)

```xml
<style type="button">
    <painter>
        <decorations>
            <decoration>
                <WebShape round="22,0,0,0" />
                <WebShadow type="outer" color="0,0,0,0" />
            </decoration>
        </decorations>
    </painter>
</style>

```

**Comment by mgarin** [comment]
This seem to be a problem with shape calculation and not shadow:
![image](https://user-images.githubusercontent.com/2361389/70633285-5dc70f00-1c41-11ea-8a24-c2a95dbbf1c6.png)

I might have an idea what causes it, but I'll have to check it. From a glance it does seem that it hits a limit of 50% of bounds height and doesn't go any further for shadow or background, while border actually doesn't care about it.

Also there is another problem you can see on screenshot above - the overkill round size is not taken into account and you can see shape stretching outside a bit. This is probably something I won't be touching as it is up to whoever makes the style to keep it sized reasonably for the given context.

**Comment by mgarin** [comment]
It seems that there are some major flaws with the shape creation on some edge cases like this one, so I'll be reworking it to fix the problem.

**Comment by mgarin** [comment]
I've already made a local fix, but I'll need to heavily test it because this change affects every single component as most of them use `WebShape` that is getting a major change. So I'll probably release somewhere mid-day tomorrow, although it will only be available on snapshot builds for now.

**Comment by mgarin** [comment]
I've somewhat finished with the fix, but it will take a bit longer to wrap all changes that I've been working on locally. It shouldn't take more than a few hours though.

Here is the result example:

![image](https://user-images.githubusercontent.com/2361389/70706308-b4d2ef80-1ce6-11ea-82a9-a0f75727c2d5.png)

Note that in case you "overshoot" with the round it will still look weird:

![image](https://user-images.githubusercontent.com/2361389/70706356-cf0ccd80-1ce6-11ea-926d-5001f1ebde95.png)

Although shadow and background will now follow border to death. You can even see that background spreads over different bounds on top three buttons which is correct considering all three shapes basically have different bounds.

I thought about maybe limiting round to height/width, but then there are still cases when two rounded corners meet on a side - what should happen then? So I'll leave it as it as for now and see if I will find any good solution for it later.

---

There are also some niche cases which might still have problems even after these changes - specifically with shadow - but I was aware of those even before you've pointed out this bug and I'll be ironing them out later. No one discovered those yet anyway and probably won't due to specifics :)

**Comment by mgarin** [comment]
I've pushed fix for this issue along with other internal changes. `WebShape` should now work in the same way for borders, backgrounds and shadow (visually).

Snapshot v1.2.12 build will be available soon.
