### ISSUE TITLE
ClassResource improvements

### ISSUE THREAD

**Issue by husker-dev** [mgarin/weblaf#620]
Now, to use ClassResource, you need to give the constructor a class to create an InputStream. 
But if you want to create an InputStream using the current class, you can omit it.

Here is an example how to it can be done in ClassResource class:
```java
public final class ClassResource implements Resource {

    ...

    public ClassResource(@NotNull String path) {
        this(getExecutableClass(), path);
    }

    ...

    private static String getExecutableClass(){
        List<String> avoid = Arrays.asList(
            Thread.class.getCanonicalName(), 
            ClassResource.class.getCanonicalName()
        );

        for (StackTraceElement element : Thread.currentThread().getStackTrace())
            if (!avoid.contains(element.getClassName()) && !element.getClassName().contains("$"))
                return element.getClassName();
        return null;
    }

}
```

And now we can reduce the XmlSkin constructor to this:

```java
public class WebLightSkin extends XmlSkin{

    public WebLightSkin (){
        super(new ClassResource("resources/web-light-skin.xml"));
    }
}
```

And if you embed ClassResource in the XmlSkin class itself, it turns out like this:

```java
public class WebLightSkin extends XmlSkin{

    public WebLightSkin (){
        super("resources/web-light-skin.xml");
    }
}
```

So it will be very easy for a beginner to start creating his skin.

According to my tests, everything seems to work as it should

**Comment by daWoife** [comment]
Why not just use this.getClass() instead of searching a call stack, so if there would be an extra constructor in XmlSkin ..

public XmlSkin ( @NotNull final String path )
{
     this ( new ClassResource ( this.getClass(), path );
}

.. you would have achieved the same without any further changes.

**Comment by husker-dev** [comment]
Yes, but it’s possible to remove this part of the code and make it cleaner

**Comment by mgarin** [comment]
It might be easier to use once, but I generally disagree that this would be a good addition. This is actually something I'm trying to actively go away from in WebLaF code/design decisions. 

The main problem - readability and maintainability of the code using a lot of such "convenient" constructors and utilities goes way down. Every time you read this:
```java
public class WebLightSkin extends XmlSkin
{
    public WebLightSkin ()
    {
        super ( "resources/web-light-skin.xml" );
    }
}
```
You will have to guess or double-check where the heck is exactly that XML coming from compared to the clear definition of the class/path reference:
```java
public class WebLightSkin extends XmlSkin
{
    public WebLightSkin ()
    {
        super ( new ClassResource ( WebLightSkin.class, "resources/web-light-skin.xml" ) );
    }
}
```

Also when you're working with 3rd-party API - 
Seeing this constructor: `XmlSkin ( String )`
Is much worse than seeing this: `XmlSkin ( Resource )`

In case with `String` you have to go and read JavaDoc and probably even peek into source code (if it is even available and you have convenient access to it). What is that `String` - pure XML? path? relative to what? It generally produces more questions than it solves. Obviously it would be convenient for me (because i've written it) or for you (because you requested it), but it's not that convenient for anyone else.

In case with `Resource` - you can easily see that it's an interface and any IDE allows you to look at available implementations in one click. There are only 3 implementations in WebLaF right now - `ClassResource`, `FileResource` and `UrlResource` which should be way more obvious to anyone.

I won't even go into why searching a call stack is a bad idea :)

---

I do understand that in some cases it's reasonable to have some additional methods/constructors for convenience, but it's not always a wise thing to add. I've done that a lot in the past with some WebLaF APIs and it led to quite a lot of wasted time later on.

**Comment by mgarin** [comment]
Regarding beginners - I would say having a set of good introduction wiki articles is a better approach compared to trying to modify the code to cater them. Unfortunately that is something that takes a lot of time and usually has lower priority than WebLaF improvements & bugfixes.

And, as a side note, I doubt any beginner would get as far as creating his own custom `Skin` without having any idea of how WebLaF works in the first place :)

**Comment by husker-dev** [comment]
I misunderstood ```daWoife```'s answer. It shows the case when ```XmlSkin``` has an ```(@NotNull String path)``` constructor. But initially, my idea was to implement a search for the called class in the ```ClassResource``` constructor. And after I gave an example of how it can be integrated into ```XmlSkin```, which was not the best solution, I agree. 

As for ClassResource, updating will not change the logic of the class itself, as it seems to me.

But I don’t understand why searching in ```StackTraces``` is a bad idea. It requires a one-time setup, and will work without fail.

**Comment by husker-dev** [comment]
Also, ```for``` can be replaced in the method with one line: 
```java
Thread.currentThread().getStackTrace()[2].getClassName();
```

But the index must be configured.

**Comment by mgarin** [comment]
To be honest - it's the same issue with `ClassResource` constructor without class as with `XmlSkin` constructor without one - it's obscure. As long as you're not familiar with the library and the specific API - you will not understand what does `new ClassResource ( String )` do, so I really don't see how it makes the API better, especially for beginners.

As for the stack usage - the issue I have with it is maintainability. Once I use it - I will have to always keep it in mind  when modifying that class. For instance - I can't just slap an extra constructor on top of the one I have as it will change the stack depth and basically produce an error that can be easily overlooked. While it might not seem a big deal in one or two cases - it gets way worse once you have a lot of such nuances across the huge library code base. 

Maintainability is one of the main issues I've stumbled on once WebLaF code exploded in size, so I take it very seriously and rather not add any questionable or "fragile" code unless it is unavoidable (which is sometimes the unfortunate reality with Swing).
