### ISSUE TITLE
Difference between Extends and Include

### ISSUE THREAD

**Issue by husker-dev** [mgarin/weblaf#623]
If, for example, I want to make my skin based on another, what should I use?
```xml
<extends>weblaf.light.skin</extends>
```
Or
```xml
<include nearClass="com.alee.skin.light.WebLightSkin">resources/web-light-skin.xml</include>
```
And what is the difference between them?

As I understand it, the difference may be that ```extends``` uses an already initialized ```skin```, and therefore use ```id```?

**Comment by mgarin** [comment]
Block `<extends>` is exclusive for `SkinExtension`s and simply specifies which `Skin`s are supported by that particular extension. Whichever skins you specify as extended will automatically use your extension (if it was registered through `StyleManager.addExtensions ( ... )`) if they are loaded at any point in runtime.

As an example, extensions used by demo application:

- [demo-light-extension.xml](https://github.com/mgarin/weblaf/blob/master/modules/demo/src/com/alee/demo/skin/resources/demo-light-extension.xml) - Extends light skin only as it is specifically tailored for it
- [demo-dark-extension.xml](https://github.com/mgarin/weblaf/blob/master/modules/demo/src/com/alee/demo/skin/resources/demo-dark-extension.xml) - Extends dark skin only as it is specifically tailored for it
- [demo-adaptive-extension.xml](https://github.com/mgarin/weblaf/blob/master/modules/demo/src/com/alee/demo/skin/resources/demo-adaptive-extension.xml) - Extends both light and dark skins as it contains some basic styles that aren't using any particular colors and are applicable for both skins

---

Block `<include>` directly imports all icon sets and styles from the specified skin XML file (including it's own includes) while ignoring all other information from that skin. 

Includes are primarily used to break skin XML file down into smaller and more readable pieces. It doesn't really matter which styles go where, but you need to keep in mind that read and parsing order of includes and directly provided styles is strict.

Here is a small example:

- `<style1>`
- `<style2>`
- `<include1>`
   - `<style1.1>`
   - `<style1.2>`
- `<style3>`
- `<style4>`

Styles will be read strictly in next order:
style1 -> style2 -> style1.1 -> style1.2 -> style3 -> style4

So, for instance, style3 and style4 can extend style1.1 and style1.2, but style1 and style2 can't. But if you position style1 and style2 after the include in the XML file - they will be able to extend style1.1 and style1.2.

**Comment by mgarin** [comment]
Also, if you're working with an IDE that supports XML syntax check based on XSD - you can add `xmlns` attribute to your skins & extensions:
- For skins: `<skin xmlns="http://weblookandfeel.com/XmlSkin">`
- For extensions: `<skin xmlns="http://weblookandfeel.com/XmlSkinExtension">`

And point IDE at:
- [XmlSkin.xsd](https://github.com/mgarin/weblaf/blob/master/modules/ui/src/com/alee/managers/style/validation/XmlSkin.xsd)
- [XmlSkinExtension.xsd](https://github.com/mgarin/weblaf/blob/master/modules/ui/src/com/alee/managers/style/validation/XmlSkinExtension.xsd)

(these are available in the `weblaf-ui` module)

**Comment by husker-dev** [comment]
So if I create skin with ```<extends>weblaf.light.skin</extends>```, then my skin settings will be applied when ```weblaf.light.skin``` is turned on?
(Thanks for .xsd files, I haven't seen them before)

**Comment by mgarin** [comment]
If you create a skin with `<extends>` block - it's not a skin, it will be an extension and it cannot be loaded as a standalone skin. It can only be used through `XmlSkinExtension` class and added into `StyleManager` after L&F initialization. If you do so - yes, your styles from that extension will be added to the set of light skin styles.

**Comment by mgarin** [comment]
Also, for a less abrupt explanation I recommend reading the styling introduction article from the wiki (if you haven't seen it yet): https://github.com/mgarin/weblaf/wiki/Styling-introduction

I also just double-checked it - it does seem to be up-to-date with the latest WebLaF release.

**Comment by husker-dev** [comment]
Not entirely related to the original question, but still interesting.

---

What happens if you specify the extension id in the ```<extends>```? 
Will it apply?
#### Example
```my.skin.id``` (**30** styles) <-```my.first.extension``` (30+**5** styles) <- ```my.second.extension``` (30+5+**7** styles)

If I register all extensions and call ```my.skin.id```, will I get 30+5+7 styles?

**Comment by mgarin** [comment]
One issue with your structure - extensions cannot extend other extensions, at least currently (and I'm not sure if that will really be necessary for any real use-case scenario) - extensions can only extend skins directly.

So if you would change your `extension2.xml` to `<extends>my.test.skin<extends>` - yes, all 42 styles will be available as long as you install your skin and register both extensions in runtime.

---

Somewhat related important note about extensions - they cannot contain overrides for styles from the main skin or other extensions currently. I don't think that WebLaF have any related checks in the code, but you will have inconsistent visual results if you try to add style overrides in extensions. You can extend any main skin styles in extensions though, there should be no issues with that. 

This will change in v1.3.0 - overrides in extensions will start working due to the change of style compiling process, for better or for worse, - in the end it will up to the user to decide how he wants to build his style structure and up to the user to support the mess he created :)

Technical details aside - I initially designed extensions to provide a way to throw some extra custom styles into the "pile" in runtime and not to modify the base skin. Mostly for applications that have plugins that can be loaded in runtime and that contain UI parts. 

But with the upcoming changes - the line will certainly blur. The main reason for the change - extensions are simply a bit more convenient for use, especially when you're not fully customizing all the styles. And it is probably very confusing right now - the difference between what you can do in skins and what you can do in extensions. We also ended up using extensions for some other initially unintended cases, for instance to provide skin-dependent (or skin-independent) styles - like in WebLaF demo application.
