### ISSUE TITLE
How can I set weblaf windows title bar theme style as default?

### ISSUE THREAD

**Issue by UltimateYZ** [mgarin/weblaf#624]
Hi weblaf,

I wanted to know how to set weblaf windows title bar style theme as default instead of the underlying OS. And also how to modify it properly (main jframe).

![Screenshot from 2020-05-16 17-47-49](https://user-images.githubusercontent.com/55871338/82124161-7cf03c80-979d-11ea-89de-bf0ebd6cfb77.png)

**Comment by mgarin** [comment]
Custom L&F frame & dialog decoration can be enabled in two ways.

1. The same way you do it with any other L&F:
```java
JFrame.setDefaultLookAndFeelDecorated ( true );
JDialog.setDefaultLookAndFeelDecorated ( true );
```
This obviously will enabled it for all of your frames/dialogs respectively.

2. Use `WebFrame` or `WebDialog` instead of `JFrame` or `JDialog` and provide a style identifier in the constructor that references a style that applies custom window decoration:
```java
final WebFrame frame = new WebFrame ( StyleId.frameDecorated );
final WebDialog dialog = new WebDialog ( StyleId.dialogDecorated );
```
With this approach decoration will be applied only to those two windows.

---

On how to re-style the decoration - I recommend reading these two wiki articles:

- [Styling introduction](https://github.com/mgarin/weblaf/wiki/Styling-introduction)
- [Window decoration](https://github.com/mgarin/weblaf/wiki/Window-decoration)

They are up-to-date with the latest released version and should cover

**Comment by UltimateYZ** [comment]
Thanks mgarin.
