### ISSUE TITLE
Problems with double windows title bar

### ISSUE THREAD

**Issue by UltimateYZ** [mgarin/weblaf#627]
Hi Mgarin,

I'm facing double windows title bar issues when my class inherits the l&f super class, WebFrame(). That only happens when I try to decorate the windows title bar frame. I don't know what I did wrong.

![Screenshot from 2020-05-18 19-01-03](https://user-images.githubusercontent.com/55871338/82240137-3257f700-993a-11ea-81cf-c760dba19dc4.png)

Here is the simple code:

![Screenshot from 2020-05-18 19-03-44](https://user-images.githubusercontent.com/55871338/82240228-57e50080-993a-11ea-895c-8eb24b1ef5b8.png)

Is WebFrame() class an internal frame?

**Comment by mgarin** [comment]
You need to provide `StyleId` before your frame becomes visible or before you call any methods on it that force it's native peer to be initialized (like `pack()`) because once the window peer is initialized - you cannot switch between native and custom window decoration. 

The best and most optimal way - provide the `StyleId` straight into constructor.

**Comment by UltimateYZ** [comment]
Thanks, it works!
