### ISSUE TITLE
Line spacing in WebStyledLabel

### ISSUE THREAD

**Issue by husker-dev** [mgarin/weblaf#640]
Is it possible to change the line spacing in the WebStyledLabel?

**Comment by mgarin** [comment]
You can, not exactly in `WebStyledLabel` but in any style that contains text which visual implementation is extending `AbstractStyledTextContent`. For those styles you can provide a `rowGap` setting.

In case of `WebStyledLabel` specifically you'd need a separate style like this:
```xml
    <style type="styledlabel" id="large-row-gap">
        <painter>
            <decorations>
                <decoration>
                    <LabelLayout>
                        <StyledLabelText constraints="text" rowGap="15" />
                    </LabelLayout>
                </decoration>
            </decorations>
        </painter>
    </style>
```

`StyledLabelText` extends `AbstractStyledTextContent` so it does have that setting, but you can also replace the text content implementation in the style for any other component - like normal `JLabel` - to be able to configure that.

**Comment by mgarin** [comment]
Regarding `rowGap` itself - it's not exactly my implementation and I haven't tried it myself, but looking by the source code - it does seem to be properly used for the lines positioning.

Code does prevent negative value from being used though, so you can't exactly reduce the gap. Whatever you see currently is the default gap and is equal to zero `rowGap` value. I can potentially look into changing that part though as it might have been an unnecessary limitation.

**Comment by mgarin** [comment]
Also, I guess it might be a good idea to expose that setting in `WebStyledLabel`, it's a pretty small and easy improvement since it has it's own `StyledLabelText` implementation.

**Comment by husker-dev** [comment]
(The question is not entirely related to the original, but related to the WebStyledLabel)

Is it possible to make the WebStyledLabel height automatically increase, based on content?

It is possible to do using setPreferredHeight, but it hardcodes the size without regard to content.

![image](https://user-images.githubusercontent.com/31825139/90507442-915a2180-e15e-11ea-80ad-d0e2eb4ae940.png)

In theory, this code should work, but something is stopping it.
```java
new WebPanel(){{
    setLayout(new BorderLayout());

    WebStyledLabel label = new WebStyledLabel("Lots of text....");
    label.setMaximumRows(6);
    label.setMaximumHeight(80);
    label.setMinimumHeight(35);
    label.setPreferredHeight(SizeMethods.UNDEFINED);
    add(label, BorderLayout.SOUTH);
}};

```

**Comment by mgarin** [comment]
> In theory, this code should work, but something is stopping it.

Unfortunately minimum/maximum methods are barely used anywhere because they don't exactly function in the way you would expect them to. Size methods were mostly designed to propose component's minimum/preferred/maximum component sizes to the underlying layout, but most components only provide preferred size and minimum/maximum are either the same or `0` and `Integer.MAX_VALUE` on both axis. And even when you forcefully set them - it is up to layout to use or ignore them. 

In case with the `WebStyledLabel` - it has to provide all those sizes without actually knowing how much space it will have within the layout. Like, will there be 200px for each line? Or 400px? Without knowing that beforehand - there is no realistic way for it to properly wrap the lines and calculated width and height. So default preferred size is when all text fits into 1 long line.

That being said, there is a workaround available in `WebStyledLabel` for this specific case you are asking about:
```
public class StyledLabelExample
{
    public static void main ( final String[] args )
    {
        SwingTest.run ( new Runnable ()
        {
            @Override
            public void run ()
            {
                final WebStyledLabel label = new WebStyledLabel ( "Sample text content" );
                label.setMaximumTextWidth ( 50 );

                TestFrame.show ( label );
            }
        } );
    }
}
```
The `setMaximumTextWidth ( int )` method will fixate maximum line width and allow `WebStyledLabel` to dynamically calculate the amount of rows it needs to have and the overall preferred height to fit them all in. Result:

![image](https://user-images.githubusercontent.com/2361389/90518551-9c697d80-e16f-11ea-96d1-5dd7dc12c082.png)

I also checked the `setMaximumRows ( int )` method - it doesn't really play well with the previously mentioned setting (and overall it still has some issues), so I wouldn't recommend using that one. There still seem to be some issues with text layouting when maximum text width is specified, will see if we can find it quickly with my colleague - I have a few ideas about what might be causing it.

**Comment by mgarin** [comment]
We found a few different issues with various wrapping cases in `AbstractStyledTextContent`, @macstrace just pushed a fix for those issues - 0a39e8c - it will be available in v1.2.14 snapshot version in a few minutes.

This should fix all problems that might appear with wrapping whenever you use `setMaximumTextWidth ( int )` and `setMaximumRows ( int )` methods together or separately, as well as some other cases which were incorrectly wrapping or trimming text.

**Comment by mgarin** [comment]
So, with those fixes in mind, the way I would recommend approaching your specific case is using `setMaximumTextWidth ( int )` to provide container width to the `WebStyledLabel` directly whenever container size changes - that is, if your container width is not static (can be changed by user or UI in runtime). Otherwise - you can simply set a fixed text width through the same method.

And in case you want to limit amount of text lines displayed - you can also use `setMaximumRows ( int )` on top of the other solution. This will allow text to expand vertically until that maximum amount of rows (text lines) is reached.

**Comment by mgarin** [comment]
I'll close this as the question should be answered.
But if you have any further related questions/issues - feel free to reopen this issue!
