### ISSUE TITLE
Dear author, WebPopupMenu and WebComboBox ,How do I change the style to what I want?

### ISSUE THREAD

**Issue by xcfdszzr** [mgarin/weblaf#674]
![image](https://user-images.githubusercontent.com/10494040/134648873-9597c840-63c0-4634-a454-6e48eb47c1d0.png)
        use WebComboBox  and WebPopupMenu ,I can't find any patterns that I need
        for example
![image](https://user-images.githubusercontent.com/10494040/134649273-9d336b7e-db9a-4da4-85e5-f4c997066acf.png)

![image](https://user-images.githubusercontent.com/10494040/134649456-ea16d215-b376-458f-a4d0-739334de5515.png)

**Comment by mgarin** [comment]
Due to complexity and some minor issues - popup menu styling haven't been switched to fully-customizable scheme yet, but it should be possible to modify it to make it look like on your 2nd screenshot.

As you correctly noticed - `popupmenu` base style can be found in `popupmenu.xml`:
https://github.com/mgarin/weblaf/blob/master/modules/ui/src/com/alee/skin/light/resources/popupmenu.xml 
It does have a limited amount of settings though because it is based on a custom `PopupMenuPainter`.

You can find all the properties you can specify in the `popupmenu` style in these two classes:
https://github.com/mgarin/weblaf/blob/master/modules/ui/src/com/alee/laf/menu/PopupMenuPainter.java
https://github.com/mgarin/weblaf/blob/master/modules/ui/src/com/alee/laf/menu/AbstractPopupPainter.java

Also it is important to note that combobox uses it's own variation of `popupmenu` style which can be found here:
https://github.com/mgarin/weblaf/blob/master/modules/ui/src/com/alee/skin/light/resources/combobox.xml#L90
It doesn't modify the base one visually though, but it can be helpful in case you want to modify only combobox popup menu.

In the future - current default painter (`PopupMenuPainter`) will be replaced with a more customizable one to allow things like shape change, custom backgrounds, states support etc.

**Comment by mgarin** [comment]
To add to my previous answer - you need these settings to specifically replicate popup from your screenshot:
```xml
<painter>
    <popupStyle>simple</popupStyle>
    <background>white</background>
    <borderColor>white</borderColor>
    <round>0</round>
    <shadeWidth>6</shadeWidth>
    <shadeOpacity>0.5</shadeOpacity>
    <opacity>1</opacity>
</painter>
```
You can either apply these painter settings to default `popupmenu` style, to the `combobox` popup menu sub-style or to any other specific separate `popupmenu` style with a custom identifier.

**Comment by mgarin** [comment]
The original question should have been answered, so I'll be closing this issue
