### ISSUE TITLE
custom toolTip

### ISSUE THREAD

**Issue by wyj3531** [mgarin/weblaf#694]
![image](https://user-images.githubusercontent.com/23471836/149734983-8512d7c5-1976-43a6-8914-15166d9cb76b.png)

**Comment by wyj3531** [comment]
can i custom its style?Background, WebShape,Line,etc.
and how to remove the arrow ,it is also happen in WebComboBox.

**Comment by mgarin** [comment]
> can i custom its style?Background, WebShape,Line,etc.

Unfortunately custom tooltips style is currently not modifiable as it is hardcoded in `WebCustomTooltip` class.
It is listed in #476 and mentioned in #520 for future improvements.

---

> and how to remove the arrow ,it is also happen in WebComboBox.

I recommend using simple Swing tooltips instead of the custom WebLaF ones if you don't want the positioning/arrow style - check the `JToolTip` section in demo:

![image](https://user-images.githubusercontent.com/2361389/149758398-8b6253a1-5461-4ba9-bc4c-8ada852a4acc.png)

You can also modify the `JToolTip` display via its style:
https://github.com/mgarin/weblaf/blob/master/modules/ui/src/com/alee/skin/light/resources/tooltip.xml

Unfortunately you can only change it's style globally as there is currently no way to change it on per-component basis. I've added a separate issue for that - #695 - which will be implemented in future versions.

**Comment by wyj3531** [comment]
how about this arrow?
![Uploading image.png…]()

**Comment by mgarin** [comment]
Combobox popup menu can be adjusted via style.
Combobox style has a child style that is attached to it's popup menu:
https://github.com/mgarin/weblaf/blob/master/modules/ui/src/com/alee/skin/light/resources/combobox.xml#L90

You can create a custom style for combobox and adjust the popup style in it:
```xml
<style type="combobox" id="custom">
    <style type="popupmenu" id="popup">
        <painter>
            <popupStyle>simple</popupStyle>
        </painter>
    </style>
</style>
```

**Comment by wyj3531** [comment]
.
