### ISSUE TITLE
The same font is blurred by shape?

### ISSUE THREAD

**Issue by xcfdszzr** [mgarin/weblaf#697]
Dear author, how should I handle this problem, online urgent waiting

             
                <style type="rootpane" id="common-frame-transparent" extends="frame">
                    <ui>
                        <installComponents>false</installComponents>
                    </ui>
                    <painter>
            
                        <decorations>
                            <decoration>
            
                                <WebShadow color="0,0,0" type="outer" opacity="0.5" width="30"/>
                            </decoration>
                            <decoration states="focused">
                                <WebShadow type="outer" opacity="0.5"/>
                            </decoration>
                            <decoration states="maximized">
                                <WebShape round="0"/>
                                <WebShadow type="outer" width="0"/>
                                <LineBorder opacity="0"/>
                            </decoration>
                            <decoration states="fullscreen">
                                <WebShape round="0"/>
                                <WebShadow type="outer" width="0"/>
                                <LineBorder opacity="0"/>
                            </decoration>
                            <decoration states="unix">
                                <WebShape round="0"/>
                                <WebShadow type="outer" width="0"/>
                                <LineBorder opacity="0"/>
                            </decoration>
                        </decorations>
                    </painter>
                    <style type="panel" id="content" extends="transparent"/>
                </style>

![image](https://user-images.githubusercontent.com/10494040/158730410-65590b01-35c8-4fcb-9cc8-b4dc92af8c0f.png)
![image](https://user-images.githubusercontent.com/10494040/158730454-1c602f51-d657-4902-a8a7-b31e13310987.png)

                          final String title = getExampleLanguagePrefix () + "content";
                          final JFrame frame = new JFrame ();
                          UILanguageManager.registerComponent ( frame.getRootPane (), title );
                          frame.getRootPane ().putClientProperty ( StyleId.STYLE_PROPERTY, getStyleId () );
                          frame.setIconImages ( WebLookAndFeel.getImages () );
                          WebLabel aaaaaaaarpa = new WebLabel("AAAAAAAARPA简单简单应用问题", WebLabel.CENTER);
                          aaaaaaaarpa.setFont(new Font("微软雅黑", Font.BOLD,16));

                          WebLabel aaaaaaaarpa2 = new WebLabel("AAAAAAAARPA简单简单应用问题", WebLabel.CENTER);
                          aaaaaaaarpa2.setFont(new Font("宋体", Font.BOLD,16));
                          frame.getContentPane().setLayout(new BorderLayout());
                          frame.getContentPane().add(aaaaaaaarpa);
                          frame.getContentPane().add(aaaaaaaarpa2,BorderLayout.NORTH);
                          frame.setAlwaysOnTop ( true );
                          frame.setSize ( 500, 400 );
                          frame.setLocationRelativeTo ( DemoApplication.getInstance () );
                          frame.setDefaultCloseOperation ( WindowConstants.DISPOSE_ON_CLOSE );
                          frame.setVisible ( true );

issus :  The same font is blurred by shape

                 StyleId.frameDecorated Shape displays the font

![image](https://user-images.githubusercontent.com/10494040/158731022-2d2656e3-83bb-4b11-a24e-cf529b5c5790.png)

               StyleId.of("common-frame-transparent")    No shape property to display font

![image](https://user-images.githubusercontent.com/10494040/158730972-355427a3-832a-46bb-a268-223d98a3dc18.png)

**Comment by mgarin** [comment]
The reason why font is blurry on the decorated frame vs undecorated one is that different font antialiasing technique is being used. Blurry one is a grayscale antialias (default Swing implementation):

![image](https://user-images.githubusercontent.com/2361389/158734923-9b0e001f-c157-449a-990a-94061e50b652.png)

The crisp one is a subpixel font antialias (native implementation):

![image](https://user-images.githubusercontent.com/2361389/158734981-cd22f294-de9a-44db-9a70-29c24c11940c.png)


Unfortunately this is a known JDK issue - subpixel font antialias simply doesn't work on non-opaque destinations, which non-opaque window is. You can check this issue for more details: #130 

There are some potential workarounds for this that can maybe be done in WebLaF, but so far I didn't find an optimal way to implement them without having some major drawbacks for performance or usability.

I could suggest a couple of options to avoid this issue:

- Avoid using custom window decoration on native windows as there are plenty of known issues with non-native window decoration in any L&F such as this font issue, window behavior, window animations missing etc. You are also taking a performance hit due to the way window is being rendered in non-opaque state.

- Use custom decoration, but avoid using non-opaque windows, only rectangular-shaped non-opaque windows, this unfortunately would mean that you can't have a fancy rounded window shape or shadow painted around it (unless there is a native shadow provided by OS, for instance in Mac OS X).

- Find a custom font for your application that will "play nicely" with grayscale antialias. I don't really have any particular recommendations, but you can definitely find fonts that render well when used with grayscale antialias. Although I'm not sure if that only applies to English or not, that is something that needs further testing. Fonts can be replaced globally via static fields in [WebLookAndFeel.java](https://github.com/mgarin/weblaf/blob/master/modules/ui/src/com/alee/laf/WebLookAndFeel.java).

Unfortunately neither of these solves the problem, these are all workarounds until we either get a better support for subpixel antialias in JDK, or I find a way to workaround it within the library.

Generally it's been a while since the last time I've looked into this issue, so I'll try to find some time and peek at possible solutions again - maybe there are some new developments on that front, or maybe I've missed something.

**Comment by xcfdszzr** [comment]
@mgarin  
![image](https://user-images.githubusercontent.com/10494040/158751632-a27b503a-2fc1-4f32-94e7-a8ba649f569e.png)

      Dear author, can you provide a custom label component to handle this, or can a higher JDK handle this problem?  
     
      Anxious processing font this problem, online anxious waiting process.....

**Comment by mgarin** [comment]
Unfortunately I don't have any solution for this right now.
Also as far as I know - higher JDK versions have the same issue.

**Comment by xcfdszzr** [comment]
@mgarin 
I am so sad about this question, but thank you for your answer. Please inform me if there is any future plan

**Comment by mgarin** [comment]
I recommend you to subscribe for #130 notifications, I'll be posting updates there once there will be any.
Will be closing this issue for now as a duplicate.
