### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by Sciss** [mgarin/weblaf#89]
Would it be possible to publish the release versions to a public repository such as [Maven Central](http://search.maven.org)? That way one could easily add a dependency on WebLAF to other projects.

**Comment by EdwardBeckett** [comment]
Roll your own... 
    mvn install:install-file -Dfile=path_to_jar -DgroupId=de.sciss \
        -DartifactId=weblaf -Dversion=1.28 -Dpackaging=jar

**Comment by Sciss** [comment]
As soon as the 1.29 version is considered done, I will publish an update…

**Comment by mgarin** [comment]
Just an info: I have lots of changes locally which are still not ready for any kind of release, but I will be getting a two-week vacation and will mostly be working towards finishing v1.29. So you can expect it going live in about two-weeks time.

**Comment by EdwardBeckett** [comment]
@Sciss Love the LAF man.. great work! You Rock

**Comment by Sciss** [comment]
@EdwardBeckett not my work but mgarin's. I just put the artifact on Maven Central.

**Comment by EdwardBeckett** [comment]
@Sciss Oh...(facepalm) (Redirect 301 @mgarin) ;)

**Comment by jitpack** [comment]
It'd be easy to publish on https://jitpack.io though it expects the pom file to be in the root directory

**Comment by parkjohnston** [comment]
any update of 1.29 on maven???

**Comment by mgarin** [comment]
Update v1.29 is not yet released, so it shouldn't be there yet. I am working hard to finish last huge chunk of changes for this update and as soon as I am finished with it I will surely take time to finally publish WebLaF to Maven properly.

**Comment by mgarin** [comment]
Just a short update on the topic here -

Thanks to help from my colleague @macstrace who is more familiar with Maven - previous (v1.28) release of WebLaF is now available in Maven Central: http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.weblookandfeel%22

Also we are preparing `1.2.9` snapshot based on `styling` branch which will also be available soon.

As you might have noticed v1.28 release is tagged as `1.2.8` version in Maven Central instead of `1.28` because we had to move to new versioning to avoid issues in future. Next release will also be tagged as `1.2.9` and you might see some of the changes mentioned in #336 coming before `1.3.0` update.

**Comment by mgarin** [comment]
Will be closing this one as all new versions and current build snapshots will now always be pushed into maven repository. 

Releases: (latest available is v1.2.8)
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.weblookandfeel%22

Snapshots: (currently from `styling` branch)
https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/
